### 第四周作业-周程杨

In [ ]:
import pandas as pd
import numpy as np
from scipy.stats import ttest_ind

In [2]:
city = pd.read_csv(r'C:\Users\MrFive1001\Documents\PycharmProjects\Kaggle\Data cleaning Assignment4\City_Zhvi_AllHomes.csv')
city.head()   # 导入city,看一下前五行数据格式

,RegionID,RegionName,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,1996-07,...,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08
0,6181,New York,NY,New York,Queens,1,NaN,NaN,NaN,NaN,...,573600,576200,578400,582200,588000,592200,592500,590200,588000,586400
1,12447,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,2,155000.0,154600.0,154400.0,154200.0,...,558200,560800,562800,565600,569700,574000,577800,580600,583000,585100
2,17426,Chicago,IL,Chicago,Cook,3,109700.0,109400.0,109300.0,109300.0,...,207800,206900,206200,205800,206200,207300,208200,209100,211000,213000
3,13271,Philadelphia,PA,Philadelphia,Philadelphia,4,50000.0,49900.0,49600.0,49400.0,...,122300,121600,121800,123300,125200,126400,127000,127400,128300,129100
4,40326,Phoenix,AZ,Phoenix,Maricopa,5,87200.0,87700.0,88200.0,88400.0,...,183800,185300,186600,188000,189100,190200,191300,192800,194500,195900

In [3]:
states = {'OH': 'Ohio', 'KY': 'Kentucky', 'AS': 'American Samoa', 'NV': 'Nevada', 'WY': 'Wyoming', 'NA': 'National', 'AL': 'Alabama', 'MD': 'Maryland', 'AK': 'Alaska', 'UT': 'Utah', 'OR': 'Oregon', 'MT': 'Montana', 'IL': 'Illinois', 'TN': 'Tennessee', 'DC': 'District of Columbia', 'VT': 'Vermont', 'ID': 'Idaho', 'AR': 'Arkansas', 'ME': 'Maine', 'WA': 'Washington', 'HI': 'Hawaii', 'WI': 'Wisconsin', 'MI': 'Michigan', 'IN': 'Indiana', 'NJ': 'New Jersey', 'AZ': 'Arizona', 'GU': 'Guam', 'MS': 'Mississippi', 'PR': 'Puerto Rico', 'NC': 'North Carolina', 'TX': 'Texas', 'SD': 'South Dakota', 'MP': 'Northern Mariana Islands', 'IA': 'Iowa', 'MO': 'Missouri', 'CT': 'Connecticut', 'WV': 'West Virginia', 'SC': 'South Carolina', 'LA': 'Louisiana', 'KS': 'Kansas', 'NY': 'New York', 'NE': 'Nebraska', 'OK': 'Oklahoma', 'FL': 'Florida', 'CA': 'California', 'CO': 'Colorado', 'PA': 'Pennsylvania', 'DE': 'Delaware', 'NM': 'New Mexico', 'RI': 'Rhode Island', 'MN': 'Minnesota', 'VI': 'Virgin Islands', 'NH': 'New Hampshire', 'MA': 'Massachusetts', 'GA': 'Georgia', 'ND': 'North Dakota', 'VA': 'Virginia'}
# 使用states这个字典来代替原city中state列的缩写
city.State = city.State.apply(lambda x:states[x])  # 利用函数映射替换
city.head()

,RegionID,RegionName,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,1996-07,...,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08
0,6181,New York,New York,New York,Queens,1,NaN,NaN,NaN,NaN,...,573600,576200,578400,582200,588000,592200,592500,590200,588000,586400
1,12447,Los Angeles,California,Los Angeles-Long Beach-Anaheim,Los Angeles,2,155000.0,154600.0,154400.0,154200.0,...,558200,560800,562800,565600,569700,574000,577800,580600,583000,585100
2,17426,Chicago,Illinois,Chicago,Cook,3,109700.0,109400.0,109300.0,109300.0,...,207800,206900,206200,205800,206200,207300,208200,209100,211000,213000
3,13271,Philadelphia,Pennsylvania,Philadelphia,Philadelphia,4,50000.0,49900.0,49600.0,49400.0,...,122300,121600,121800,123300,125200,126400,127000,127400,128300,129100
4,40326,Phoenix,Arizona,Phoenix,Maricopa,5,87200.0,87700.0,88200.0,88400.0,...,183800,185300,186600,188000,189100,190200,191300,192800,194500,195900

In [4]:
list(open(r'C:\Users\MrFive1001\Documents\PycharmProjects\Kaggle\Data cleaning Assignment4\university_towns.txt'))

['Alabama[edit]\n',
 'Auburn (Auburn University)[1]\n',
 'Florence (University of North Alabama)\n',
 'Jacksonville (Jacksonville State University)[2]\n',
 'Livingston (University of West Alabama)[2]\n',
 'Montevallo (University of Montevallo)[2]\n',
 'Troy (Troy University)[2]\n',
 'Tuscaloosa (University of Alabama, Stillman College, Shelton State)[3][4]\n',
 'Tuskegee (Tuskegee University)[5]\n',
 'Alaska[edit]\n',
 'Fairbanks (University of Alaska Fairbanks)[2]\n',
 'Arizona[edit]\n',
 'Flagstaff (Northern Arizona University)[6]\n',
 'Tempe (Arizona State University)\n',
 'Tucson (University of Arizona)\n',
 'Arkansas[edit]\n',
 'Arkadelphia (Henderson State University, Ouachita Baptist University)[2]\n',
 'Conway (Central Baptist College, Hendrix College, University of Central Arkansas)[2]\n',
 'Fayetteville (University of Arkansas)[7]\n',
 'Jonesboro (Arkansas State University)[8]\n',
 'Magnolia (Southern Arkansas University)[2]\n',
 'Monticello (University of Arkansas at Monticello)[2]\n',
 'Russellville (Arkansas Tech University)[2]\n',
 'Searcy (Harding University)[5]\n',
 'California[edit]\n',
 'Angwin (Pacific Union College)[2]\n',
 'Arcata (Humboldt State University)[5]\n',
 'Berkeley (University of California, Berkeley)[5]\n',
 'Chico (California State University, Chico)[2]\n',
 'Claremont (Claremont McKenna College, Pomona College, Harvey Mudd College, Scripps College, Pitzer College, Keck Graduate Institute, Claremont Graduate University)[5]\n',
 'Cotati (California State University, Sonoma)[2]\n',
 'Davis (University of California, Davis)[1]\n',
 'Irvine (University of California, Irvine)\n',
 'Isla Vista (University of California, Santa Barbara)[2]\n',
 'University Park, Los Angeles (University of Southern California)\n',
 'Merced (University of California, Merced)\n',
 'Orange (Chapman University)\n',
 'Palo Alto (Stanford University)\n',
 'Pomona (Cal Poly Pomona, WesternU)[9][10][11] and formerly Pomona College\n',
 'Redlands (University of Redlands)\n',
 'Riverside (University of California, Riverside, California Baptist University, La Sierra University)\n',
 'Sacramento (California State University, Sacramento)\n',
 'University District, San Bernardino (California State University, San Bernardino, American Sports University)\n',
 'San Diego (University of California, San Diego, San Diego State University)\n',
 'San Luis Obispo (California Polytechnic State University)[2]\n',
 'Santa Barbara (Fielding Graduate University, Santa Barbara City College, University of California, Santa Barbara, Westmont College)[2]\n',
 'Santa Cruz (University of California, Santa Cruz)[2]\n',
 'Turlock (California State University, Stanislaus)\n',
 'Westwood, Los Angeles (University of California, Los Angeles)[2]\n',
 'Whittier (Whittier CollegeRio Hondo College)\n',
 'Colorado[edit]\n',
 'Alamosa (Adams State College)[2]\n',
 'Boulder (University of Colorado at Boulder)[12]\n',
 'Durango (Fort Lewis College)[2]\n',
 'Fort Collins (Colorado State University)[13]\n',
 'Golden (Colorado School of Mines)\n',
 'Grand Junction (Colorado Mesa University)\n',
 'Greeley (University of Northern Colorado)\n',
 'Gunnison (Western State College)[2]\n',
 'Pueblo, Colorado (Colorado State University-Pueblo)\n',
 'Connecticut[edit]\n',
 'Fairfield (Fairfield University, Sacred Heart University)\n',
 'Middletown (Wesleyan University)\n',
 'New Britain (Central Connecticut State University)\n',
 'New Haven (Yale University, University of New Haven, Southern Connecticut State University, Albertus Magnus College, Quinnipiac University)[14]\n',
 'New London (Connecticut College, US Coast Guard Academy, Mitchell College)[2]\n',
 'Storrs (University of Connecticut)[2]\n',
 'Willimantic (Eastern Connecticut State University)[2]\n',
 'Delaware[edit]\n',
 'Dover (Delaware State University)[1]\n',
 'Newark (University of Delaware)[1]\n',
 'Florida[edit]\n',
 'Ave Maria (Ave Maria University)\n',
 'Boca Raton (Florida Atlantic University)\n',
 'Coral Gables (University of Miami)\n',
 'DeLand (Stetson University)[5]\n',
 'Estero (Florida Gulf Coast University)\n',
 'Gainesville (University of Florida, Santa Fe College)\n',
 'Orlando (University of Central Florida)\n',
 'Sarasota (New College of Florida, Ringling College of Art and Design, State College of Florida, Manatee-Sarasota, University of South Florida Sarasota-Manatee)\n',
 'St. Augustine (Flagler College)\n',
 'St. Leo (St. Leo University)\n',
 'Tallahassee (Florida State University, Florida A&M University)\n',
 'Tampa (University of South Florida)\n',
 'Georgia[edit]\n',
 'Albany (Albany State University)\n',
 'Athens (University of Georgia)[15]\n',
 'Atlanta (Georgia State University, Georgia Tech, Emory)[2]\n',
 'Carrollton (University of West Georgia)[2]*Dahlonega (North Georgia College & State University)[2]\n',
 'Demorest (Piedmont College)[2]\n',
 'Fort Valley (Fort Valley State University)[2]\n',
 'Kennesaw (Kennesaw State University)\n',
 'Milledgeville (Georgia College & State University)[2]\n',
 'Mount Vernon (Brewton-Parker College)[2]\n',
 'Oxford (Oxford College)\n',
 'Rome (Berry College, Shorter University)\n',
 'Savannah (Armstrong Atlantic State University, Savannah State University, Savannah College of Art and Design)\n',
 'Statesboro (Georgia Southern University)[5]\n',
 'Valdosta (Valdosta State University)[2]\n',
 'Waleska (Reinhardt College)[2]\n',
 'Young Harris (Young Harris College)[2]\n',
 'Hawaii[edit]\n',
 'Manoa (University of Hawaii at Manoa)[2]\n',
 'Idaho[edit]\n',
 'Moscow (University of Idaho)[2]\n',
 'Pocatello (Idaho State University)[2]\n',
 'Rexburg (BYU-Idaho)[2]\n',
 'Illinois[edit]\n',
 'Carbondale (Southern Illinois University Carbondale)[5]\n',
 'Champaign鈥揢rbana (University of Illinois at Urbana鈥揅hampaign)[5]\n',
 'Charleston (Eastern Illinois University)[2]\n',
 'DeKalb (Northern Illinois University)[2]\n',
 'Edwardsville (Southern Illinois University Edwardsville)[2]\n',
 'Evanston (Northwestern University)[2]\n',
 'Lebanon (McKendree University)[2]\n',
 'Macomb (Western Illinois University)[2]\n',
 'Normal (Illinois State University)[2]\n',
 'Peoria (Bradley University)\n',
 'Indiana[edit]\n',
 'Bloomington (Indiana University Bloomington)[5]\n',
 'Crawfordsville (Wabash College)\n',
 'Greencastle (DePauw University)[5]\n',
 'Hanover (Hanover College)[2]\n',
 'Marion (Indiana Wesleyan University)[2]\n',
 'Muncie (Ball State University)[2]\n',
 'Oakland City (Oakland City University)[2]\n',
 'Richmond (Earlham College)[2]\n',
 'South Bend (Notre Dame University[2])\n',
 'Terre Haute (Indiana State University, Rose-Hulman Institute of Technology)[2]\n',
 'Upland (Taylor University)[2]\n',
 'Valparaiso (Valparaiso University)\n',
 'West Lafayette (Purdue University)[2]\n',
 'Iowa[edit]\n',
 'Ames (Iowa State University)[2]\n',
 'Cedar Falls (University of Northern Iowa)[2]\n',
 'Cedar Rapids, Iowa (Coe College )\n',
 'Decorah (Luther College)[5]\n',
 'Fayette (Upper Iowa University)[2]\n',
 'Grinnell (Grinnell College)[15]\n',
 'Iowa City (University of Iowa)[15]\n',
 'Lamoni (Graceland University)[2]\n',
 'Mount Vernon, (Cornell College)\n',
 'Orange City (Northwestern College)[2]\n',
 'Sioux Center (Dordt College)[2]\n',
 'Storm Lake (Buena Vista University)[2]\n',
 'Waverly (Wartburg College)[2]\n',
 'Kansas[edit]\n',
 'Baldwin City (Baker University)[5]\n',
 'Emporia (Emporia State University)[2]\n',
 'Hays (Fort Hays State University)[2]\n',
 'Lawrence (University of Kansas, Haskell Indian Nations University)[15]\n',
 'Manhattan (Kansas State University, Manhattan Christian College)[15]\n',
 'Pittsburg (Pittsburg State University)[2]\n',
 'Kentucky[edit]\n',
 'Bowling Green (Western Kentucky University)[2]\n',
 'Columbia (Lindsey Wilson College)[2]\n',
 'Georgetown (Georgetown College)\n',
 'Highland Heights (Northern Kentucky University)\n',
 'Lexington (University of Kentucky, Transylvania University[5]\n',
 'Louisville (University of Louisville)\n',
 'Morehead (Morehead State University)[2]\n',
 'Murray (Murray State University)[5]\n',
 'Richmond (Eastern Kentucky University)[2]\n',
 'Williamsburg (University of the Cumberlands)[2]\n',
 'Wilmore (Asbury University, Asbury Theological Seminary)[2]\n',
 'Louisiana[edit]\n',
 'Baton Rouge (Louisiana State University, Southern University)\n',
 'Grambling (Grambling State University)[5]\n',
 'Hammond (Southeastern Louisiana University)[2]\n',
 'Lafayette (University of Louisiana at Lafayette)\n',
 'Monroe (University of Louisiana at Monroe)[2]\n',
 'Natchitoches (Northwestern State University)[2]\n',
 'Ruston (Louisiana Tech University)[2]\n',
 'Thibodaux (Nicholls State University)[2]\n',
 'Maine[edit]\n',
 'Augusta (University of Maine at Augusta)[2]\n',
 'Bar Harbor (College of the Atlantic)\n',
 'Brunswick (Bowdoin College)\n',
 'Farmington (University of Maine at Farmington)[2]\n',
 'Fort Kent (University of Maine at Fort Kent)\n',
 'Gorham (University of Southern Maine)[2]\n',
 'Lewiston, Maine (Bates College)\n',
 'Orono (University of Maine)[2]\n',
 'Waterville (Thomas College, Colby College)\n',
 'Maryland[edit]\n',
 "Annapolis (United States Naval Academy, St. John's College)\n",
 'Chestertown (Washington College)[2]\n',
 'College Park (University of Maryland, College Park)[16]\n',
 'Cumberland (Allegany College of Maryland)\n',
 "Emmitsburg (Mount St. Mary's University)[2]\n",
 'Frostburg (Frostburg State University)[5]\n',
 'Princess Anne (University of Maryland Eastern Shore)[5]\n',
 'Towson (Towson University, Goucher College)[2]\n',
 'Salisbury (Salisbury University)[2]\n',
 'Westminster (McDaniel College)\n',
 'Massachusetts[edit]\n',
 'Boston (Boston University, Boston College, Boston Conservatory, New England Conservatory, Brandeis University, Northeastern University, UMass Boston, Emmanuel College, Bunker Hill Community College, Roxbury Community College, Suffolk University, Simmons College, among many others)\n',
 'Bridgewater (Bridgewater State College)[2]\n',
 'Cambridge (Harvard University, Massachusetts Institute of Technology)(Lesley University, Cambridge College, Longy School of Music)[15]\n',
 'Chestnut Hill (Boston College)\n',
 'The Colleges of Worcester Consortium:\n',
 'Dudley (Nichols College)\n',
 'North Grafton (Cummings School of Veterinary Medicine at Tufts University)\n',
 'Paxton (Anna Maria College)\n',
 'Worcester (Assumption, Becker, Clark University, Holy Cross, Mass. College of Pharmacy & Health Sciences, Quinsigamond Community College, UMass Medical School, Worcester State University, Worcester Polytechnic Institute)\n',
 'The Five College Region of Western Massachusetts:\n',
 'Amherst (Amherst College, Hampshire College, University of Massachusetts Amherst)[15]\n',
 'Northampton (Smith College)\n',
 'South Hadley (Mount Holyoke College)\n',
 'Fitchburg (Fitchburg State College)\n',
 'North Adams (Massachusetts College of Liberal Arts)\n',
 'Springfield (American International College), (Springfield College), and (Western New England College)\n',
 'Waltham (Bentley University), (Brandeis University)\n',
 'Williamstown (Williams College)\n',
 'Framingham (Framingham State University)\n',
 'Michigan[edit]\n',
 'Adrian (Adrian College, Siena Heights University)\n',
 'Albion (Albion College)[17]\n',
 'Allendale (Grand Valley State University)\n',
 'Alma (Alma College)\n',
 'Ann Arbor (University of Michigan)[1]\n',
 'Berrien Springs (Andrews University)[2]\n',
 'Big Rapids (Ferris State University)[2]\n',
 'East Lansing (Michigan State University)[2]\n',
 'Flint (Kettering University, University of Michigan-Flint)\n',
 'Hillsdale (Hillsdale College)\n',
 'Houghton (Michigan Technological University)[5]\n',
 'Kalamazoo (Western Michigan University, Kalamazoo College)[2]\n',
 'Marquette (Northern Michigan University)[2]\n',
 'Midland (Northwood University)\n',
 'Mount Pleasant (Central Michigan University)[2]\n',
 'Olivet (Olivet College)[2]\n',
 'Saginaw (Saginaw Valley State University)\n',
 'Sault Ste. Marie (Lake Superior State University)\n',
 'Spring Arbor (Spring Arbor University)[2]\n',
 'Ypsilanti (Eastern Michigan University)[2]\n',
 'Minnesota[edit]\n',
 'Bemidji (Bemidji State University)[2]\n',
 'Crookston (University of Minnesota Crookston)[2]\n',
 'Duluth (University of Minnesota Duluth, Lake Superior College, The College of St. Scholastica, University of Wisconsin鈥揝uperior, Duluth Business University\n',
 'Faribault, South Central College\n',
 'Mankato (Minnesota State University, Mankato),[2] Bethany Lutheran College\n',
 'Marshall (Southwest Minnesota State University)[2]\n',
 'Moorhead (Minnesota State University, Moorhead, Concordia College)[18]\n',
 'Morris (University of Minnesota Morris)[2]\n',
 'Northfield (Carleton College, St. Olaf College)[5]\n',
 'North Mankato, South Central College\n',
 'St. Cloud (St. Cloud State University, The College of St. Scholastica)[2]\n',
 'St. Joseph (College of Saint Benedict)[2]\n',
 'St. Peter (Gustavus Adolphus College)[2]\n',
 "Winona (Winona State University, St. Mary's University of Minnesota)[19]\n",
 'Mississippi[edit]\n',
 'Cleveland (Delta State University)[2]\n',
 'Hattiesburg (University of Southern Mississippi)[20]\n',
 'Itta Bena (Mississippi Valley State University)[2]\n',
 'Oxford (University of Mississippi)[2]\n',
 'Starkville (Mississippi State University)[2]\n',
 'Missouri[edit]\n',
 'Bolivar (Southwest Baptist University)[2]\n',
 'Cape Girardeau (Southeast Missouri State University)[2]\n',
 'Columbia (University of Missouri, Stephens College, Columbia College)[20]\n',
 'Fayette (Central Methodist University)[2]\n',
 'Fulton (Westminster College and William Woods University).\n',
 'Kirksville (Truman State University, A. T. Still University)[2]\n',
 'Maryville (Northwest Missouri State University)[2]\n',
 'Rolla (Missouri University of Science and Technology)[2]\n',
 'Warrensburg (University of Central Missouri)[5]\n',
 'Montana[edit]\n',
 'Bozeman (Montana State University)[2]\n',
 'Dillon (University of Montana Western)[2]\n',
 'Missoula (University of Montana)[5]\n',
 'Nebraska[edit]\n',
 'Chadron (Chadron State College)[5]\n',
 'Crete (Doane College)[2]\n',
 'Kearney (University of Nebraska at Kearney)[2]\n',
 'Lincoln (University of Nebraska at Lincoln)[5]\n',
 'Peru (Peru State College)[2]\n',
 'Seward (Concordia University)[2]\n',
 'Wayne (Wayne State College)[2]\n',
 'Nevada[edit]\n',
 'Las Vegas (University of Nevada, Las Vegas)\n',
 'Reno (University of Nevada, Reno)\n',
 'New Hampshire[edit]\n',
 'New London, New Hampshire (Colby-Sawyer College)\n',
 'Durham (University of New Hampshire)[2]\n',
 'Hanover (Dartmouth College)[5]\n',
 'Henniker (New England College)\n',
 'Keene (Keene State College)[2]\n',
 'Plymouth (Plymouth State University)[2]\n',
 'Rindge (Franklin Pierce University)\n',
 'New Jersey[edit]\n',
 'Ewing (The College of New Jersey), (Rider University)\n',
 "Jersey City (New Jersey City University), (Saint Peter's University)\n",
 'Glassboro (Rowan University)[2]\n',
 'Hoboken (Stevens Institute of Technology)\n',
 'Madison (Drew University), (Fairleigh Dickinson University), (College of Saint Elizabeth)\n',
 'Newark (Rutgers University), (New Jersey Institute of Technology), (UMDNJ)\n',
 'New Brunswick (Rutgers University)[5]\n',
 'Princeton (Princeton University)[5]\n',
 'Union (Kean University)\n',
 'West Long Branch (Monmouth University)\n',
 'New Mexico[edit]\n',
 'Hobbs (University of the Southwest)[2]\n',
 'Las Cruces (New Mexico State University)[2]\n',
 'Las Vegas (New Mexico Highlands University)[2]\n',
 'Portales (Eastern New Mexico University)[2]\n',
 'Silver City (Western New Mexico University)[2]\n',
 'New York[edit]\n',
 'Alfred (Alfred University, Alfred State College)[2]\n',
 'Albany (SUNY Albany, Siena College, Albany College of Pharmacy, Albany Law School, Albany Medical College, College of Saint Rose, Excelsior College, Maria College of Albany, Mildred Elley, Sage College of Albany)\n',
 'Aurora (Wells College)[21]\n',
 'Binghamton (Binghamton University)[2]\n',
 'Brockport (SUNY Brockport)[5]\n',
 'Buffalo (University at Buffalo)\n',
 'Canton (St. Lawrence University, SUNY Canton)[2]\n',
 'Clinton (Hamilton College)[2]\n',
 'Cobleskill (SUNY Cobleskill)[2]\n',
 'Delhi (SUNY Delhi)[2]\n',
 'Fredonia (SUNY Fredonia)[2]\n',
 'Geneseo (SUNY Geneseo)[2]\n',
 'Geneva (Hobart and William Smith Colleges)\n',
 'Hamilton (Colgate University)[2]\n',
 'Ithaca (Cornell University, Ithaca College)[1]\n',
 'Morningside Heights, Manhattan (Columbia University, Barnard College, Teachers College, Manhattan School of Music, Jewish Theological Seminary, Union Theological Seminary, Bank Street College of Education)\n',
 'New Paltz (SUNY New Paltz)[2]\n',
 'Oneonta (SUNY Oneonta, Hartwick College)[2]\n',
 'Oswego (SUNY Oswego)[2]\n',
 'Plattsburgh (SUNY Plattsburgh)[2]\n',
 'Potsdam (SUNY Potsdam, Clarkson University)[2]\n',
 'Poughkeepsie (Vassar College, Marist College)[2]\n',
 'Purchase (Purchase College, Manhattanville College)[2]\n',
 'Rochester (University of Rochester, Rochester Institute of Technology, Nazareth College, St. John Fisher College, Monroe Community College, Roberts Wesleyan College, SUNY Brockport, SUNY Empire State College)[2]\n',
 'Saratoga Springs (Skidmore College)[2]\n',
 'Seneca Falls (New York Chiropractic College)\n',
 'Stony Brook (Stony Brook University)\n',
 'Syracuse (Syracuse University, SUNY ESF, Upstate Medical University)\n',
 'Tivoli (Bard College)\n',
 'Troy (Rensselaer Polytechnic Institute, Russell Sage College, Hudson Valley Community College)\n',
 'West Point (United States Military Academy)\n',
 'North Carolina[edit]\n',
 'Banner Elk (Lees-McRae College)\n',
 'Boiling Springs (Gardner-Webb University)[2]\n',
 'Boone (Appalachian State University)[2]\n',
 'Buies Creek (Campbell University)[2]\n',
 'Chapel Hill (University of North Carolina at Chapel Hill)[20]\n',
 'Cullowhee (Western Carolina University)[2]\n',
 'Davidson (Davidson College)[5]\n',
 'Durham (Duke University, North Carolina Central University)[5]\n',
 'Elon (Elon University)[2]\n',
 'Greensboro (University of North Carolina at Greensboro, Greensboro College, Guilford College, North Carolina A & T State University, Bennett College)\n',
 'Greenville (East Carolina University)[2]\n',
 'Hickory (Lenoir-Rhyne University)[2]\n',
 'Mars Hill (Mars Hill College)[2]\n',
 'Mount Olive (Mount Olive College)[2]\n',
 'Pembroke (University of North Carolina at Pembroke)[2]\n',
 'Wilmington, North Carolina (University of North Carolina at Wilmington)\n',
 'Wingate (Wingate University)[2]\n',
 'Winston-Salem (Wake Forest University, University of North Carolina School of the Arts, Salem College, Winston-Salem State University)\n',
 'North Dakota[edit]\n',
 'Fargo (North Dakota State University)[18]\n',
 'Grand Forks (University of North Dakota)[5]\n',
 'Ohio[edit]\n',
 'Ada (Ohio Northern University)[2]\n',
 'Alliance (University of Mount Union)\n',
 'Ashland (Ashland University)[2]\n',
 'Athens (Ohio University)[2]\n',
 'Berea (Baldwin Wallace College)\n',
 'Bluffton (Bluffton University)[2]\n',
 'Bowling Green (Bowling Green State University)[2]\n',
 'Cedarville (Cedarville University)[2]\n',
 'Columbus (Ohio State University)\n',
 'Delaware (Ohio Wesleyan University)\n',
 'Fairborn (Wright State University)\n',
 'Findlay (University of Findlay)\n',
 'Gambier (Kenyon College)[2]\n',
 'Granville (Denison University)[2]\n',
 'Hiram (Hiram College)[2]\n',
 'Kent (Kent State University)[2]\n',
 'Nelsonville (Hocking College)[2]\n',
 'New Concord (Muskingum College)[2]\n',
 'Oberlin (Oberlin College)[5]\n',
 'Oxford (Miami University)[5]\n',
 'Rio Grande (University of Rio Grande)[2]\n',
 'Wilberforce (Wilberforce University, Central State University)[2]\n',
 'Oklahoma[edit]\n',
 'Ada (East Central University)[2]\n',
 'Alva (Northwestern Oklahoma State University)[2]\n',
 'Durant (Southeastern Oklahoma State University)[2]\n',

In [5]:
# 知道了我们要处理的文档的结构，就可以想一下怎么把数据分成两列,使用左括号把每一行分成两列
# 这里可以使用正则表达式来处理第二行
import re
r1 = re.compile('\[[^\]]*\]')  # 去除第一列的[]  或着使用'\[.*'
r2 = re.compile('\).*')
town = pd.read_table(r'C:\Users\MrFive1001\Documents\PycharmProjects\Kaggle\Data cleaning Assignment4\university_towns.txt',
                     header= None,names = ["State", "RegionName"],sep = r'(',
                     converters = {'State': (lambda x:r1.sub('',x) if x else np.nan),'RegionName':(lambda x:r2.sub('',x) if x else np.nan)}) 
# 使用了converters函数来对每一行处理
town

,State,RegionName
0,Alabama,NaN
1,Auburn,Auburn University
2,Florence,University of North Alabama
3,Jacksonville,Jacksonville State University
4,Livingston,University of West Alabama
5,Montevallo,University of Montevallo
6,Troy,Troy University
7,Tuscaloosa,"University of Alabama, Stillman College, Shelt..."
8,Tuskegee,Tuskegee University
9,Alaska,NaN
10,Fairbanks,University of Alaska Fairbanks
11,Arizona,NaN
12,Flagstaff,Northern Arizona University
13,Tempe,Arizona State University
14,Tucson,University of Arizona
15,Arkansas,NaN
16,Arkadelphia,"Henderson State University, Ouachita Baptist U..."
17,Conway,"Central Baptist College, Hendrix College, Univ..."
18,Fayetteville,University of Arkansas
19,Jonesboro,Arkansas State University
20,Magnolia,Southern Arkansas University
21,Monticello,University of Arkansas at Monticello
22,Russellville,Arkansas Tech University
23,Searcy,Harding University
24,California,NaN
25,Angwin,Pacific Union College
26,Arcata,Humboldt State University
27,Berkeley,"University of California, Berkeley"
28,Chico,"California State University, Chico"
29,Claremont,"Claremont McKenna College, Pomona College, Har..."
...,...,...
537,Cheney,Eastern Washington University
538,Ellensburg,Central Washington University
539,Pullman,Washington State University
540,"University District, Seattle",University of Washington
541,West Virginia,NaN
542,Athens,Concord University
543,Buckhannon,West Virginia Wesleyan College
544,Fairmont,Fairmont State University
545,Glenville,Glenville State College
546,Huntington,Marshall University
547,Montgomery,West Virginia University Institute of Technology
548,Morgantown,West Virginia University
549,Shepherdstown,Shepherd University
550,West Liberty,West Liberty University
551,Wisconsin,NaN
552,Appleton,Lawrence University
553,Eau Claire,University of Wisconsin–Eau Claire
554,Green Bay,University of Wisconsin-Green Bay
555,La Crosse,"University of Wisconsin–La Crosse, Western Tec..."
556,Madison,University of Wisconsin–Madison
557,Menomonie,University of Wisconsin–Stout
558,Milwaukee,"Marquette University, University of Wisconsin–..."
559,Oshkosh,University of Wisconsin–Oshkosh
560,Platteville,University of Wisconsin–Platteville
561,River Falls,University of Wisconsin–River Falls
562,Stevens Point,University of Wisconsin–Stevens Point
563,Waukesha,Carroll University
564,Whitewater,University of Wisconsin–Whitewater
565,Wyoming,NaN
566,Laramie,University of Wyoming

In [6]:
gdp = pd.read_excel(r'C:\Users\MrFive1001\Documents\PycharmProjects\Kaggle\Data cleaning Assignment4\gdplev.xls',skiprows=range(5))
#得到一个下列数据
gdp

,Unnamed: 0,GDP in billions of current dollars,GDP in billions of chained 2009 dollars,Unnamed: 3,Unnamed: 4,GDP in billions of current dollars.1,GDP in billions of chained 2009 dollars.1,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1929.0,104.6,1056.6,NaN,1947q1,243.1,1934.5,NaN
3,1930.0,92.2,966.7,NaN,1947q2,246.3,1932.3,NaN
4,1931.0,77.4,904.8,NaN,1947q3,250.1,1930.3,NaN
5,1932.0,59.5,788.2,NaN,1947q4,260.3,1960.7,NaN
6,1933.0,57.2,778.3,NaN,1948q1,266.2,1989.5,NaN
7,1934.0,66.8,862.2,NaN,1948q2,272.9,2021.9,NaN
8,1935.0,74.3,939.0,NaN,1948q3,279.5,2033.2,NaN
9,1936.0,84.9,1060.5,NaN,1948q4,280.7,2035.3,NaN
10,1937.0,93.0,1114.6,NaN,1949q1,275.4,2007.5,NaN
11,1938.0,87.4,1077.7,NaN,1949q2,271.7,2000.8,NaN
12,1939.0,93.5,1163.6,NaN,1949q3,273.3,2022.8,NaN
13,1940.0,102.9,1266.1,NaN,1949q4,271.0,2004.7,NaN
14,1941.0,129.4,1490.3,NaN,1950q1,281.2,2084.6,NaN
15,1942.0,166.0,1771.8,NaN,1950q2,290.7,2147.6,NaN
16,1943.0,203.1,2073.7,NaN,1950q3,308.5,2230.4,NaN
17,1944.0,224.6,2239.4,NaN,1950q4,320.3,2273.4,NaN
18,1945.0,228.2,2217.8,NaN,1951q1,336.4,2304.5,NaN
19,1946.0,227.8,1960.9,NaN,1951q2,344.5,2344.5,NaN
20,1947.0,249.9,1939.4,NaN,1951q3,351.8,2392.8,NaN
21,1948.0,274.8,2020.0,NaN,1951q4,356.6,2398.1,NaN
22,1949.0,272.8,2008.9,NaN,1952q1,360.2,2423.5,NaN
23,1950.0,300.2,2184.0,NaN,1952q2,361.4,2428.5,NaN
24,1951.0,347.3,2360.0,NaN,1952q3,368.1,2446.1,NaN
25,1952.0,367.7,2456.1,NaN,1952q4,381.2,2526.4,NaN
26,1953.0,389.7,2571.4,NaN,1953q1,388.5,2573.4,NaN
27,1954.0,391.1,2556.9,NaN,1953q2,392.3,2593.5,NaN
28,1955.0,426.2,2739.0,NaN,1953q3,391.7,2578.9,NaN
29,1956.0,450.1,2797.4,NaN,1953q4,386.5,2539.8,NaN
...,...,...,...,...,...,...,...,...
250,NaN,NaN,NaN,NaN,2009q1,14383.9,14375.0,NaN
251,NaN,NaN,NaN,NaN,2009q2,14340.4,14355.6,NaN
252,NaN,NaN,NaN,NaN,2009q3,14384.1,14402.5,NaN
253,NaN,NaN,NaN,NaN,2009q4,14566.5,14541.9,NaN
254,NaN,NaN,NaN,NaN,2010q1,14681.1,14604.8,NaN
255,NaN,NaN,NaN,NaN,2010q2,14888.6,14745.9,NaN
256,NaN,NaN,NaN,NaN,2010q3,15057.7,14845.5,NaN
257,NaN,NaN,NaN,NaN,2010q4,15230.2,14939.0,NaN
258,NaN,NaN,NaN,NaN,2011q1,15238.4,14881.3,NaN
259,NaN,NaN,NaN,NaN,2011q2,15460.9,14989.6,NaN
260,NaN,NaN,NaN,NaN,2011q3,15587.1,15021.1,NaN
261,NaN,NaN,NaN,NaN,2011q4,15785.3,15190.3,NaN
262,NaN,NaN,NaN,NaN,2012q1,15973.9,15291.0,NaN
263,NaN,NaN,NaN,NaN,2012q2,16121.9,15362.4,NaN
264,NaN,NaN,NaN,NaN,2012q3,16227.9,15380.8,NaN
265,NaN,NaN,NaN,NaN,2012q4,16297.3,15384.3,NaN
266,NaN,NaN,NaN,NaN,2013q1,16475.4,15491.9,NaN
267,NaN,NaN,NaN,NaN,2013q2,16541.4,15521.6,NaN
268,NaN,NaN,NaN,NaN,2013q3,16749.3,15641.3,NaN
269,NaN,NaN,NaN,NaN,2013q4,16999.9,15793.9,NaN
270,NaN,NaN,NaN,NaN,2014q1,17025.2,15747.0,NaN
271,NaN,NaN,NaN,NaN,2014q2,17285.6,15900.8,NaN
272,NaN,NaN,NaN,NaN,2014q3,17569.4,16094.5,NaN
273,NaN,NaN,NaN,NaN,2014q4,17692.2,16186.7,NaN
274,NaN,NaN,NaN,NaN,2015q1,17783.6,16269.0,NaN
275,NaN,NaN,NaN,NaN,2015q2,17998.3,16374.2,NaN
276,NaN,NaN,NaN,NaN,2015q3,18141.9,16454.9,NaN
277,NaN,NaN,NaN,NaN,2015q4,18222.8,16490.7,NaN
278,NaN,NaN,NaN,NaN,2016q1,18281.6,16525.0,NaN
279,NaN,NaN,NaN,NaN,2016q2,18450.1,16583.1,NaN

In [7]:
#我们需要抛弃第0，1行，第4，7列
# gdp = gdp.iloc[list((range(len(gdp.index))) - [0,1]),(list(range(len(gdp.columns)))-[3,4,7])] 不能使用
gdp = ((gdp.drop(gdp.index[0:2],axis = 0)).drop(gdp.columns[3:4].append(gdp.columns[7:8]),axis = 1)) #注意注意index连接方式append
gdp

,Unnamed: 0,GDP in billions of current dollars,GDP in billions of chained 2009 dollars,Unnamed: 4,GDP in billions of current dollars.1,GDP in billions of chained 2009 dollars.1
2,1929.0,104.6,1056.6,1947q1,243.1,1934.5
3,1930.0,92.2,966.7,1947q2,246.3,1932.3
4,1931.0,77.4,904.8,1947q3,250.1,1930.3
5,1932.0,59.5,788.2,1947q4,260.3,1960.7
6,1933.0,57.2,778.3,1948q1,266.2,1989.5
7,1934.0,66.8,862.2,1948q2,272.9,2021.9
8,1935.0,74.3,939.0,1948q3,279.5,2033.2
9,1936.0,84.9,1060.5,1948q4,280.7,2035.3
10,1937.0,93.0,1114.6,1949q1,275.4,2007.5
11,1938.0,87.4,1077.7,1949q2,271.7,2000.8
12,1939.0,93.5,1163.6,1949q3,273.3,2022.8
13,1940.0,102.9,1266.1,1949q4,271.0,2004.7
14,1941.0,129.4,1490.3,1950q1,281.2,2084.6
15,1942.0,166.0,1771.8,1950q2,290.7,2147.6
16,1943.0,203.1,2073.7,1950q3,308.5,2230.4
17,1944.0,224.6,2239.4,1950q4,320.3,2273.4
18,1945.0,228.2,2217.8,1951q1,336.4,2304.5
19,1946.0,227.8,1960.9,1951q2,344.5,2344.5
20,1947.0,249.9,1939.4,1951q3,351.8,2392.8
21,1948.0,274.8,2020.0,1951q4,356.6,2398.1
22,1949.0,272.8,2008.9,1952q1,360.2,2423.5
23,1950.0,300.2,2184.0,1952q2,361.4,2428.5
24,1951.0,347.3,2360.0,1952q3,368.1,2446.1
25,1952.0,367.7,2456.1,1952q4,381.2,2526.4
26,1953.0,389.7,2571.4,1953q1,388.5,2573.4
27,1954.0,391.1,2556.9,1953q2,392.3,2593.5
28,1955.0,426.2,2739.0,1953q3,391.7,2578.9
29,1956.0,450.1,2797.4,1953q4,386.5,2539.8
30,1957.0,474.9,2856.3,1954q1,385.9,2528.0
31,1958.0,482.0,2835.3,1954q2,386.7,2530.7
...,...,...,...,...,...,...
250,NaN,NaN,NaN,2009q1,14383.9,14375.0
251,NaN,NaN,NaN,2009q2,14340.4,14355.6
252,NaN,NaN,NaN,2009q3,14384.1,14402.5
253,NaN,NaN,NaN,2009q4,14566.5,14541.9
254,NaN,NaN,NaN,2010q1,14681.1,14604.8
255,NaN,NaN,NaN,2010q2,14888.6,14745.9
256,NaN,NaN,NaN,2010q3,15057.7,14845.5
257,NaN,NaN,NaN,2010q4,15230.2,14939.0
258,NaN,NaN,NaN,2011q1,15238.4,14881.3
259,NaN,NaN,NaN,2011q2,15460.9,14989.6
260,NaN,NaN,NaN,2011q3,15587.1,15021.1
261,NaN,NaN,NaN,2011q4,15785.3,15190.3
262,NaN,NaN,NaN,2012q1,15973.9,15291.0
263,NaN,NaN,NaN,2012q2,16121.9,15362.4
264,NaN,NaN,NaN,2012q3,16227.9,15380.8
265,NaN,NaN,NaN,2012q4,16297.3,15384.3
266,NaN,NaN,NaN,2013q1,16475.4,15491.9
267,NaN,NaN,NaN,2013q2,16541.4,15521.6
268,NaN,NaN,NaN,2013q3,16749.3,15641.3
269,NaN,NaN,NaN,2013q4,16999.9,15793.9
270,NaN,NaN,NaN,2014q1,17025.2,15747.0
271,NaN,NaN,NaN,2014q2,17285.6,15900.8
272,NaN,NaN,NaN,2014q3,17569.4,16094.5
273,NaN,NaN,NaN,2014q4,17692.2,16186.7
274,NaN,NaN,NaN,2015q1,17783.6,16269.0
275,NaN,NaN,NaN,2015q2,17998.3,16374.2
276,NaN,NaN,NaN,2015q3,18141.9,16454.9
277,NaN,NaN,NaN,2015q4,18222.8,16490.7
278,NaN,NaN,NaN,2016q1,18281.6,16525.0
279,NaN,NaN,NaN,2016q2,18450.1,16583.1

In [8]:
# 我们再把gdp分为两部分
gdp_year = gdp.iloc[:,0:3].dropna(how = 'all').copy()
gdp_year.index = range(len(gdp_year.index))
gdp_year.columns = ['year','GDP1','GDP2']
gdp_year

      year     GDP1     GDP2
0   1929.0    104.6   1056.6
1   1930.0     92.2    966.7
2   1931.0     77.4    904.8
3   1932.0     59.5    788.2
4   1933.0     57.2    778.3
5   1934.0     66.8    862.2
6   1935.0     74.3    939.0
7   1936.0     84.9   1060.5
8   1937.0     93.0   1114.6
9   1938.0     87.4   1077.7
10  1939.0     93.5   1163.6
11  1940.0    102.9   1266.1
12  1941.0    129.4   1490.3
13  1942.0    166.0   1771.8
14  1943.0    203.1   2073.7
15  1944.0    224.6   2239.4
16  1945.0    228.2   2217.8
17  1946.0    227.8   1960.9
18  1947.0    249.9   1939.4
19  1948.0    274.8   2020.0
20  1949.0    272.8   2008.9
21  1950.0    300.2   2184.0
22  1951.0    347.3   2360.0
23  1952.0    367.7   2456.1
24  1953.0    389.7   2571.4
25  1954.0    391.1   2556.9
26  1955.0    426.2   2739.0
27  1956.0    450.1   2797.4
28  1957.0    474.9   2856.3
29  1958.0    482.0   2835.3
..     ...      ...      ...
57  1986.0   4590.2   7860.5
58  1987.0   4870.2   8132.6
59  1988.0   5252.6   8474.5
60  1989.0   5657.7   8786.4
61  1990.0   5979.6   8955.0
62  1991.0   6174.0   8948.4
63  1992.0   6539.3   9266.6
64  1993.0   6878.7   9521.0
65  1994.0   7308.8   9905.4
66  1995.0   7664.1  10174.8
67  1996.0   8100.2  10561.0
68  1997.0   8608.5  11034.9
69  1998.0   9089.2  11525.9
70  1999.0   9660.6  12065.9
71  2000.0  10284.8  12559.7
72  2001.0  10621.8  12682.2
73  2002.0  10977.5  12908.8
74  2003.0  11510.7  13271.1
75  2004.0  12274.9  13773.5
76  2005.0  13093.7  14234.2
77  2006.0  13855.9  14613.8
78  2007.0  14477.6  14873.7
79  2008.0  14718.6  14830.4
80  2009.0  14418.7  14418.7
81  2010.0  14964.4  14783.8
82  2011.0  15517.9  15020.6
83  2012.0  16155.3  15354.6
84  2013.0  16691.5  15612.2
85  2014.0  17393.1  15982.3
86  2015.0  18036.6  16397.2

[87 rows x 3 columns]

In [9]:
gdp_quarter = gdp.iloc[:,3:].copy()
gdp_quarter.columns = ['year_quarter','GDP1','GDP2']
gdp_quarter.index = range(len(gdp_quarter.index))
gdp_quarter

    year_quarter     GDP1     GDP2
0         1947q1    243.1   1934.5
1         1947q2    246.3   1932.3
2         1947q3    250.1   1930.3
3         1947q4    260.3   1960.7
4         1948q1    266.2   1989.5
5         1948q2    272.9   2021.9
6         1948q3    279.5   2033.2
7         1948q4    280.7   2035.3
8         1949q1    275.4   2007.5
9         1949q2    271.7   2000.8
10        1949q3    273.3   2022.8
11        1949q4    271.0   2004.7
12        1950q1    281.2   2084.6
13        1950q2    290.7   2147.6
14        1950q3    308.5   2230.4
15        1950q4    320.3   2273.4
16        1951q1    336.4   2304.5
17        1951q2    344.5   2344.5
18        1951q3    351.8   2392.8
19        1951q4    356.6   2398.1
20        1952q1    360.2   2423.5
21        1952q2    361.4   2428.5
22        1952q3    368.1   2446.1
23        1952q4    381.2   2526.4
24        1953q1    388.5   2573.4
25        1953q2    392.3   2593.5
26        1953q3    391.7   2578.9
27        1953q4    386.5   2539.8
28        1954q1    385.9   2528.0
29        1954q2    386.7   2530.7
..           ...      ...      ...
248       2009q1  14383.9  14375.0
249       2009q2  14340.4  14355.6
250       2009q3  14384.1  14402.5
251       2009q4  14566.5  14541.9
252       2010q1  14681.1  14604.8
253       2010q2  14888.6  14745.9
254       2010q3  15057.7  14845.5
255       2010q4  15230.2  14939.0
256       2011q1  15238.4  14881.3
257       2011q2  15460.9  14989.6
258       2011q3  15587.1  15021.1
259       2011q4  15785.3  15190.3
260       2012q1  15973.9  15291.0
261       2012q2  16121.9  15362.4
262       2012q3  16227.9  15380.8
263       2012q4  16297.3  15384.3
264       2013q1  16475.4  15491.9
265       2013q2  16541.4  15521.6
266       2013q3  16749.3  15641.3
267       2013q4  16999.9  15793.9
268       2014q1  17025.2  15747.0
269       2014q2  17285.6  15900.8
270       2014q3  17569.4  16094.5
271       2014q4  17692.2  16186.7
272       2015q1  17783.6  16269.0
273       2015q2  17998.3  16374.2
274       2015q3  18141.9  16454.9
275       2015q4  18222.8  16490.7
276       2016q1  18281.6  16525.0
277       2016q2  18450.1  16583.1

[278 rows x 3 columns]

In [10]:
_recession_start = []
_recession_end = []
_recession_bottom = []
start_flag,end_flag = 0,0
g_data = gdp_quarter.GDP1.values
d_data = gdp_quarter.year_quarter.values
for i in range(1,len(gdp_quarter.index)):
    if g_data[i] <= g_data[i-1] and start_flag == 0:
        start_flag = 1
    elif g_data[i] <= g_data[i-1] and start_flag == 1:
        start_flag = 2
        _recession_start.append(d_data[i-2])
        low = d_data[i]
    elif g_data[i] <= g_data[i-1] and start_flag == 2:
        low = d_data[i] if d_data[i] <= low else low
    elif g_data[i] > g_data[i-1] and start_flag == 0:
        continue
    elif g_data[i] > g_data[i-1] and start_flag == 1:
        start_flag = 0
    elif g_data[i] > g_data[i-1] and start_flag == 2:
        if end_flag == 0:
            end_flag = 1
        else:
            end_flag = 0
            start_flag = 0
            _recession_end.append(d_data[i-2])
            _recession_bottom.append(low)
#正常状态需要对最后一个值进行特殊吹的，但是嫌麻烦，而且在这个数据下没有必要。

In [11]:
_recession_start,_recession_end,_recession_bottom

(['1948q4', '1953q2', '1957q3', '2008q3'],
 ['1949q3', '1954q1', '1958q1', '2009q2'],
 ['1949q2', '1953q4', '1958q1', '2009q1'])

In [12]:
house = city.groupby(["State","RegionName"]).mean()
# 这里看出有重复的地址所以我们取平均来得到数据
house

                           RegionID  SizeRank   1996-04   1996-05   1996-06  \
State     RegionName
Alabama   Adamsville        10040.0    5345.0   60200.0   60800.0   61000.0
          Alabaster         43839.0    1681.0  108400.0  108300.0  107800.0
          Albertville        8332.0    1562.0   67500.0   67200.0   66900.0
          Arab              35038.0    3088.0   75000.0   74600.0   74400.0
          Ardmore           57107.0    5434.0       NaN       NaN       NaN
          Axis              23564.0    8800.0       NaN       NaN       NaN
          Baileyton         44007.0    9915.0       NaN       NaN       NaN
          Bay Minette        3562.0    3031.0   66300.0   66500.0   68100.0
          Bayou La Batre    10284.0    9802.0   41000.0   40300.0   40100.0
          Bessemer          16997.0    2126.0       NaN       NaN       NaN
          Birmingham        10417.0     121.0   46000.0   45900.0   45900.0
          Boaz               3732.0    5094.0   66000.0   65600.0   65000.0
          Brent              3798.0    7768.0   79800.0   79900.0   80200.0
          Brighton          37574.0    7866.0       NaN       NaN       NaN
          Brookwood          3842.0    6498.0   88600.0   87100.0   86500.0
          Buhl              17223.0    9867.0   81300.0   81000.0   81900.0
          Calera            44402.0    3510.0   91700.0   91800.0   91900.0
          Center Point      44519.0    4544.0   67600.0   67800.0   68100.0
          Centreville       44535.0    6329.0   80700.0   80700.0   80700.0
          Chalkville       103474.0    9021.0   78400.0   78800.0   78600.0
          Chancellor         4043.0    9286.0       NaN       NaN       NaN
          Chelsea           37845.0   10036.0  147300.0  146000.0  144300.0
          Chickasaw         30870.0    5026.0   44700.0   45000.0   45300.0
          Chunchula          8211.0    7950.0   62900.0   64000.0   65100.0
          Citronelle        48822.0    4417.0   53400.0   53000.0   52900.0
          Clay              57092.0    9838.0   99700.0   99700.0  100300.0
          Coden             24145.0    9558.0   56200.0   55800.0   55800.0
          Coker             44672.0    9145.0  108500.0  107600.0  107900.0
          Concord           37993.0    9949.0   68000.0   67400.0   67300.0
          Cottondale        36819.0    3883.0   92800.0   92700.0   92200.0
...                             ...       ...       ...       ...       ...
Wisconsin Vandenbroek      397632.0   10040.0       NaN       NaN       NaN
          Vernon           398534.0    6233.0       NaN       NaN       NaN
          Vienna           398543.0    8355.0       NaN  141700.0  143300.0
          Vinland          396938.0    7990.0  121200.0  124500.0  126400.0
          Wales             48303.0   10358.0       NaN       NaN       NaN
          Waterford        399085.0    6457.0  147000.0  145100.0  144200.0
          Waukesha          34683.0     820.0       NaN       NaN       NaN
          Waunakee          34685.0    7610.0       NaN  151400.0  153400.0
          Waupun            55059.0    2964.0   64900.0   66600.0   67700.0
          Wausau            14501.0    1654.0   54800.0   55900.0   56700.0
          Wayne            397462.0    8088.0       NaN       NaN       NaN
          West Allis        34721.0     655.0   73200.0   74200.0   75200.0
          Weston            21260.0    4210.0   68500.0   68400.0   68800.0
          Wheatland        398205.0    6744.0  110500.0  109500.0  108500.0
          Whitelaw          29264.0    8934.0   78000.0   81400.0   82100.0
          Williams Bay      41713.0    9098.0  147500.0  146600.0  145900.0
          Wilson           226870.0    8889.0  107300.0  104500.0  102900.0
          Wind Lake         15992.0    7225.0  147500.0  145000.0  143100.0
          Wind Point       254727.0    9465.0  167500.0  166800.0  166000.0
          Wisconsin Dells   29435.0    5828.0   86800.0   86400.0   86400.0
          Wolf River       397938.0    9637.0   93100.0   92500.0   92300.0
          Woodruff          34904.0    7430.0       NaN       NaN       NaN
          Woodville         14720.0    8590.0       NaN       NaN       NaN
          Yorkville        398781.0    5902.0  163000.0  162400.0  161200.0
Wyoming   Bar Nunn          50851.0   10603.0       NaN       NaN       NaN
          Burns             23888.0   10092.0       NaN       NaN       NaN
          Casper             4002.0     576.0       NaN       NaN       NaN
          Cheyenne          44571.0     375.0       NaN       NaN       NaN
          Evansville        11364.0    9984.0       NaN       NaN       NaN
          Pine Bluffs       19945.0   10032.0       NaN       NaN       NaN

                            1996-07   1996-08   1996-09   1996-10   1996-11  \
State     RegionName
Alabama   Adamsville        60500.0   60200.0   60400.0   60600.0   60400.0
          Alabaster        107500.0  107300.0  107000.0  107200.0  107600.0
          Albertville       66200.0   65600.0   65100.0   64800.0   64600.0
          Arab              73900.0   73500.0   73800.0   74300.0   74700.0
          Ardmore               NaN       NaN       NaN       NaN       NaN
          Axis                  NaN       NaN       NaN       NaN       NaN
          Baileyton             NaN       NaN       NaN       NaN       NaN
          Bay Minette       69400.0   69500.0   68700.0   68500.0   68600.0
          Bayou La Batre    39600.0   39100.0   38700.0   38200.0   37600.0
          Bessemer              NaN       NaN       NaN       NaN       NaN
          Birmingham        46000.0   46000.0   46100.0   46000.0   45900.0
          Boaz              63500.0   62000.0   61000.0   60200.0   59600.0
          Brent             81000.0   82200.0   83100.0   83600.0   84400.0
          Brighton              NaN       NaN       NaN       NaN       NaN
          Brookwood         86800.0   87200.0   86600.0   85900.0   86300.0
          Buhl              82800.0   82900.0   82500.0   82000.0   81200.0
          Calera            91900.0   91700.0   91000.0   90200.0   90100.0
          Center Point      68500.0   69000.0   69200.0   69600.0   70100.0
          Centreville       81700.0   83700.0   84600.0   84900.0   85800.0
          Chalkville        78500.0   78700.0   78900.0   79400.0   80200.0
          Chancellor            NaN       NaN       NaN       NaN       NaN
          Chelsea          142900.0  142200.0  142300.0  142200.0  141900.0
          Chickasaw         45400.0   45300.0   45100.0   45100.0   45200.0
          Chunchula         65900.0   66300.0   67000.0   68000.0   68600.0
          Citronelle        52800.0   52700.0   53000.0   53300.0   53100.0
          Clay             101100.0  101500.0  102100.0  102600.0  103100.0
          Coden             55800.0   55000.0   53600.0   52700.0   52300.0
          Coker            108400.0  107200.0  106400.0  107000.0  107600.0
          Concord           68000.0   68800.0   69200.0   69300.0   69500.0
          Cottondale        91800.0   91700.0   91400.0   91200.0   91500.0
...                             ...       ...       ...       ...       ...
Wisconsin Vandenbroek           NaN       NaN       NaN       NaN       NaN
          Vernon                NaN       NaN       NaN       NaN       NaN
          Vienna           144500.0  145500.0  146600.0  148500.0  149300.0
          Vinland          127000.0  126800.0  127500.0  128200.0  127400.0
          Wales                 NaN       NaN       NaN       NaN       NaN
          Waterford        143900.0  143600.0  142600.0  140900.0  139800.0
          Waukesha              NaN       NaN       NaN       NaN       NaN
          Waunakee         154200.0  154500.0  154700.0  154900.0  154800.0
          Waupun            68900.0   69700.0   70000.0   70500.0   71300.0
          Wausau            57200.0   57300.0   56900.0   56200.0   55500.0
          Wayne                 NaN       NaN       NaN       NaN       NaN
          West Allis        75400.0   74900.0   74800.0   75200.0   75500.0
          Weston            69500.0   70300.0   70400.0   69900.0   68800.0
          Wheatland        108200.0  108500.0  108600.0  108400.0  108200.0
          Whitelaw          81700.0   82500.0   83700.0   83700.0   83600.0
          Williams Bay     145500.0  145100.0  143800.0  142800.0  142800.0
          Wilson           102200.0  102500.0  102500.0  102000.0  102100.0
          Wind Lake        143500.0  144200.0  143200.0  141800.0  141700.0
          Wind Point       164700.0  163600.0  162500.0  162300.0  162300.0
          Wisconsin Dells   86800.0   87600.0   88500.0   89200.0   89500.0
          Wolf River        93100.0   94300.0   95100.0   94700.0   93800.0
          Woodruff              NaN       NaN       NaN       NaN       NaN
          Woodville             NaN       NaN       NaN       NaN       NaN
          Yorkville        159200.0  158200.0  157700.0  157000.0  155700.0
Wyoming   Bar Nunn              NaN       NaN       NaN       NaN       NaN
          Burns                 NaN       NaN       NaN       NaN       NaN
          Casper                NaN       NaN       NaN       NaN       NaN
          Cheyenne              NaN       NaN       NaN       NaN       NaN
          Evansville            NaN       NaN       NaN       NaN       NaN
          Pine Bluffs           NaN       NaN       NaN       NaN       NaN

                             ...      2015-11   2015-12   2016-01   2016-02  \
State     RegionName         ...
Alabama   Adamsville         ...      73900.0   73500.0   73600.0   74100.0
          Alabaster          ...     151800.0  152400.0  152800.0  153400.0
          Albertville        ...      91600.0   91500.0   91400.0   92000.0
          Arab               ...     112500.0  112100.0  111000.0  109800.0
          Ardmore            ...     144200.0  143100.0  142200.0  142500.0
          Axis               ...     109500.0  109000.0  109600.0  110300.0
          Baileyton          ...      97200.0   97400.0   97200.0   96600.0
          Bay Minette        ...     121700.0  122000.0  121300.0  120300.0
          Bayou La Batre     ...      48900.0   48600.0   48700.0   48700.0
          Bessemer           ...      59500.0   59600.0   59600.0   59800.0
          Birmingham         ...      63200.0   62600.0   62400.0   62000.0
          Boaz               ...      86700.0   86400.0   85700.0   85700.0
          Brent              ...      96000.0   95200.0   94400.0   94700.0
          Brighton           ...      45900.0   45300.0   44700.0   44800.0
          Brookwood          ...     118400.0  118100.0  116600.0  114900.0
          Buhl               ...     146400.0  146300.0  142300.0  138900.0
          Calera             ...     128500.0  128800.0  129300.0  129700.0
          Center Point       ...      80800.0   81100.0   81600.0   82000.0
          Centreville        ...     101900.0  102200.0  103300.0  103700.0
          Chalkville         ...     111300.0  110600.0  110800.0  111700.0
          Chancellor         ...     110000.0  109700.0  110900.0  113200.0
          Chelsea            ...     208000.0  208600.0  209100.0  209000.0
          Chickasaw          ...      58500.0   58400.0   58100.0   57700.0
          Chunchula          ...     123800.0  123100.0  122800.0  122500.0
          Citronelle         ...      94100.0   93200.0   93000.0   93400.0
          Clay               ...     141700.0  142200.0  142700.0  143000.0
          Coden              ...      80500.0   80300.0   80700.0   81200.0
          Coker              ...     155300.0  155400.0  152800.0  150400.0
          Concord            ...     111000.0  112300.0  112800.0  112400.0
          Cottondale         ...     138000.0  138000.0  136100.0  134000.0
...                          ...          ...       ...       ...       ...
Wisconsin Vandenbroek        ...     206400.0  208000.0  208700.0  209900.0
          Vernon             ...     263200.0  263300.0  262800.0  263700.0
          Vienna             ...     282000.0  281800.0  281600.0  284200.0
          Vinland            ...     182100.0  182300.0  182500.0  183000.0
          Wales              ...     267600.0  267600.0  266900.0  267800.0
          Waterford          ...     230200.0  229800.0  230300.0  230400.0
          Waukesha           ...     190500.0  190900.0  190500.0  190900.0
          Waunakee           ...     297500.0  297300.0  297700.0  299600.0
          Waupun             ...     109800.0  109500.0  109400.0  110600.0
          Wausau             ...      94700.0   93700.0   93600.0   93700.0
          Wayne              ...     256600.0  258000.0  259800.0  262200.0
          West Allis         ...      99900.0  101700.0  102000.0  100800.0
          Weston             ...     138800.0  139000.0  139800.0  140300.0
          Wheatland          ...     176200.0  177500.0  179200.0  182300.0
          Whitelaw           ...     117900.0  118200.0  117800.0  117200.0
          Williams Bay       ...     225700.0  226600.0  229100.0  230700.0
          Wilson             ...     177400.0  178800.0  179250.0  179500.0
          Wind Lake          ...     241700.0  241700.0  241600.0  240700.0
          Wind Point         ...     249400.0  252000.0  254000.0  254100.0
          Wisconsin Dells    ...     140600.0  139700.0  139400.0  139700.0
          Wolf River         ...     163200.0  162100.0  160200.0  159300.0
          Woodruff           ...     165600.0  163900.0  162800.0  162400.0
          Woodville          ...     182100.0  183000.0  183100.0  182400.0
          Yorkville          ...     244100.0  246500.0  248800.0  248800.0
Wyoming   Bar Nunn           ...     211500.0  211200.0  211200.0  210300.0
          Burns              ...     164100.0  164500.0  166800.0  168500.0
          Casper             ...     182300.0  182600.0  184000.0  184500.0
          Cheyenne           ...     190500.0  191900.0  193800.0  194700.0
          Evansville         ...     303900.0  306600.0  308200.0  309700.0
          Pine Bluffs        ...     169600.0  169300.0  168400.0  166300.0

                            2016-03   2016-04   2016-05   2016-06   2016-07  \
State     RegionName
Alabama   Adamsville        74800.0   75200.0   74900.0   74700.0   74700.0
          Alabaster        154200.0  154900.0  155200.0  155200.0  155600.0
          Albertville       92600.0   92600.0   92400.0   92400.0   92300.0
          Arab             109300.0  109500.0  110100.0  110700.0  111600.0
          Ardmore          143000.0  143200.0  143400.0  143100.0  142300.0
          Axis             110900.0  111700.0  112300.0  112600.0  112800.0
          Baileyton         96500.0   97500.0   99100.0  100100.0  101300.0
          Bay Minette      119200.0  118500.0  118300.0  118200.0  118300.0
          Bayou La Batre    48300.0   47800.0   47800.0   47900.0   47600.0
          Bessemer          59900.0   59700.0   59900.0   60000.0   59900.0
          Birmingham        61700.0   61600.0   61700.0   61600.0   61300.0
          Boaz              86500.0   87100.0   87300.0   87700.0   88300.0
          Brent             94200.0   93200.0   91500.0   89400.0   87900.0
          Brighton          45600.0   45500.0   44400.0   43400.0   43700.0
          Brookwood        114200.0  113500.0  111900.0  110500.0  109200.0
          Buhl             138200.0  137500.0  135800.0  133400.0  130000.0
          Calera           129900.0  130000.0  130000.0  129800.0  129600.0
          Center Point      82500.0   82800.0   83000.0   83300.0   83800.0
          Centreville      102700.0  101500.0  100400.0   99000.0   98400.0
          Chalkville       113000.0  113800.0  114400.0  115000.0  115600.0
          Chancellor       115800.0  118800.0  120800.0  121400.0  121500.0
          Chelsea          209500.0  210500.0  211500.0  212200.0  213500.0
          Chickasaw         57500.0   57200.0   57000.0   57000.0   56800.0
          Chunchula        122200.0  122500.0  123400.0  124100.0  124300.0
          Citronelle        93700.0   93900.0   94000.0   94000.0   93800.0
          Clay             143400.0  144000.0  144500.0  145000.0  145600.0
          Coden             81400.0   81900.0   82300.0   81900.0   81000.0
          Coker            149700.0  149000.0  147200.0  145400.0  144000.0
          Concord          111800.0  111500.0  111700.0  112600.0  113600.0
          Cottondale       133400.0  133900.0  134200.0  134000.0  133600.0
...                             ...       ...       ...       ...       ...
Wisconsin Vandenbroek      212100.0  214400.0  216800.0  218800.0  221700.0
          Vernon           265500.0  266900.0  268400.0  269200.0  272000.0
          Vienna           286600.0  286100.0  285500.0  285800.0  288100.0
          Vinland          183900.0  185100.0  186400.0  188000.0  189400.0
          Wales            270600.0  273400.0  276200.0  277400.0  280300.0
          Waterford        230900.0  233200.0  235200.0  236100.0  237000.0
          Waukesha         192000.0  193200.0  194200.0  194500.0  197000.0
          Waunakee         300800.0  301600.0  303200.0  304600.0  306700.0
          Waupun           112300.0  112800.0  112600.0  112400.0  112600.0
          Wausau            94500.0   95800.0   96900.0   97800.0   98200.0
          Wayne            263600.0  264900.0  266900.0  269600.0  271700.0
          West Allis        99900.0  100000.0   97900.0   95800.0   95600.0
          Weston           140400.0  140900.0  142100.0  143700.0  144700.0
          Wheatland        185200.0  187300.0  189000.0  190700.0  193000.0
          Whitelaw         116700.0  116800.0  117400.0  118000.0  117800.0
          Williams Bay     234900.0  242800.0  250100.0  252300.0  254000.0
          Wilson           180550.0  182750.0  186100.0  189350.0  191550.0
          Wind Lake        240200.0  242000.0  244000.0  245600.0  247700.0
          Wind Point       255100.0  258300.0  260900.0  259300.0  258100.0
          Wisconsin Dells  140200.0  140700.0  140900.0  141400.0  142500.0
          Wolf River       159000.0  158800.0  160200.0  163800.0  167100.0
          Woodruff         162400.0  161900.0  161600.0  162400.0  163700.0
          Woodville        182400.0  184000.0  186700.0  189300.0  192000.0
          Yorkville        247800.0  250400.0  255300.0  259900.0  264100.0
Wyoming   Bar Nunn         209100.0  209000.0  209000.0  208500.0  207700.0
          Burns            169500.0  171100.0  172100.0  171600.0  170700.0
          Casper           184500.0  184900.0  185400.0  185200.0  184600.0
          Cheyenne         194800.0  195500.0  196400.0  197600.0  198800.0
          Evansville       310400.0  310200.0  308800.0  308600.0  308800.0
          Pine Bluffs      165800.0  166600.0  164500.0  160300.0  158000.0

                            2016-08
State     RegionName
Alabama   Adamsville        74700.0
          Alabaster        156100.0
          Albertville       92100.0
          Arab             112400.0
          Ardmore          141600.0
          Axis             112700.0
          Baileyton        103100.0
          Bay Minette      118700.0
          Bayou La Batre    47200.0
          Bessemer          59700.0
          Birmingham        61200.0
          Boaz              88900.0
          Brent             87400.0
          Brighton          44300.0
          Brookwood        108100.0
          Buhl             126700.0
          Calera           129600.0
          Center Point      84200.0
          Centreville       98600.0
          Chalkville       115800.0
          Chancellor       121500.0
          Chelsea          214900.0
          Chickasaw         56400.0
          Chunchula        124400.0
          Citronelle        93700.0
          Clay             146100.0
          Coden             80100.0

In [13]:
house = house.loc[:,'2000-01':]
house

                            2000-01   2000-02   2000-03   2000-04   2000-05  \
State     RegionName
Alabama   Adamsville        68700.0   69100.0   69300.0   69200.0   69100.0
          Alabaster        121600.0  122300.0  122500.0  122800.0  123200.0
          Albertville       74300.0   74100.0   73500.0   72700.0   72500.0
          Arab              84500.0   83900.0   82900.0   81900.0   81400.0
          Ardmore               NaN       NaN       NaN       NaN       NaN
          Axis                  NaN       NaN       NaN       NaN       NaN
          Baileyton             NaN       NaN       NaN       NaN       NaN
          Bay Minette       82900.0   81700.0   80500.0   79200.0   78200.0
          Bayou La Batre    44000.0   44100.0   44100.0   44200.0   44600.0
          Bessemer              NaN       NaN       NaN       NaN       NaN
          Birmingham        53900.0   54000.0   54200.0   54300.0   54400.0
          Boaz              70900.0   70900.0   70800.0   70400.0   70200.0
          Brent             92500.0   92800.0   93500.0   94400.0   94400.0
          Brighton              NaN       NaN       NaN       NaN       NaN
          Brookwood         92500.0   92200.0   93000.0   94300.0   95000.0
          Buhl              90900.0   90400.0   91100.0   93100.0   94900.0
          Calera           108300.0  109300.0  109200.0  109900.0  110900.0
          Center Point      80800.0   81000.0   81100.0   80900.0   81200.0
          Centreville       95200.0   95000.0   95700.0   96800.0   96700.0
          Chalkville        93900.0   94100.0   94300.0   94300.0   94500.0
          Chancellor            NaN       NaN       NaN       NaN       NaN
          Chelsea          160000.0  161800.0  164400.0  166600.0  167200.0
          Chickasaw         50300.0   51200.0   52100.0   53100.0   53800.0
          Chunchula         79800.0   80200.0   80800.0   81800.0   81800.0
          Citronelle        63900.0   64700.0   65900.0   66700.0   66400.0
          Clay             120400.0  121100.0  121200.0  121400.0  122200.0
          Coden             62300.0   62500.0   63000.0   64100.0   65200.0
          Coker            116400.0  118000.0  119900.0  121300.0  121000.0
          Concord           78800.0   78400.0   78600.0   78500.0   78600.0
          Cottondale       100500.0  100800.0  101200.0  102000.0  102700.0
...                             ...       ...       ...       ...       ...
Wisconsin Vandenbroek           NaN       NaN       NaN       NaN       NaN
          Vernon           183200.0  183800.0  182600.0  180500.0  178100.0
          Vienna           177100.0  177800.0  179200.0  181200.0  181800.0
          Vinland          117900.0  119600.0  121900.0  124400.0  126600.0
          Wales                 NaN       NaN       NaN       NaN       NaN
          Waterford        122000.0  121000.0  120600.0  119900.0  119200.0
          Waukesha         141400.0  141700.0  140700.0  139700.0  138400.0
          Waunakee         186100.0  187400.0  188700.0  190200.0  191800.0
          Waupun            83700.0   84200.0   84100.0   83900.0   83900.0
          Wausau            68500.0   69800.0   70400.0   70000.0   69200.0
          Wayne                 NaN       NaN       NaN       NaN       NaN
          West Allis        80600.0   80900.0   81300.0   81600.0   81700.0
          Weston            79200.0   79900.0   81400.0   82300.0   82700.0
          Wheatland        128800.0  129500.0  131100.0  131800.0  131800.0
          Whitelaw          94800.0   96100.0   97200.0   98800.0  101200.0
          Williams Bay     127100.0  122600.0  119000.0  116900.0  115400.0
          Wilson           128100.0  129200.0  129800.0  129300.0  129000.0
          Wind Lake        125200.0  124000.0  123900.0  123500.0  123400.0
          Wind Point       150800.0  148800.0  148100.0  147400.0  145400.0
          Wisconsin Dells   98300.0  100000.0  101700.0  102600.0  103500.0
          Wolf River        93700.0   95100.0   96700.0   98200.0   99300.0
          Woodruff              NaN       NaN       NaN       NaN       NaN
          Woodville             NaN       NaN       NaN       NaN       NaN
          Yorkville        140400.0  138800.0  138000.0  136500.0  134700.0
Wyoming   Bar Nunn          93400.0   93100.0   92600.0   91000.0   89300.0
          Burns            100900.0  101300.0  102400.0  103600.0  104400.0
          Casper            88400.0   89300.0   90000.0   90100.0   89600.0
          Cheyenne         116000.0  116700.0  117900.0  119200.0  120100.0
          Evansville       128500.0  128100.0  127500.0  127700.0  128600.0
          Pine Bluffs       93900.0   93400.0   93900.0   94900.0   95300.0

                            2000-06   2000-07   2000-08   2000-09   2000-10  \
State     RegionName
Alabama   Adamsville        69200.0   69500.0   69700.0   70200.0   71100.0
          Alabaster        123200.0  123100.0  123100.0  123300.0  123500.0
          Albertville       72600.0   72500.0   72800.0   73200.0   73500.0
          Arab              81400.0   81200.0   81200.0   81600.0   82400.0
          Ardmore               NaN       NaN       NaN       NaN       NaN
          Axis                  NaN       NaN       NaN       NaN       NaN
          Baileyton             NaN       NaN       NaN       NaN       NaN
          Bay Minette       78200.0   78400.0   79100.0   79900.0   80700.0
          Bayou La Batre    44700.0   44600.0   44300.0   43900.0   43900.0
          Bessemer              NaN       NaN       NaN       NaN       NaN
          Birmingham        54500.0   54700.0   55000.0   55200.0   55600.0
          Boaz              70200.0   70100.0   70100.0   70700.0   71000.0
          Brent             94200.0   94800.0   96400.0   97300.0   98100.0
          Brighton              NaN       NaN       NaN       NaN       NaN
          Brookwood         96000.0   97700.0   99100.0   99800.0  100100.0
          Buhl              95800.0   96400.0   96600.0   96500.0   96500.0
          Calera           110300.0  109000.0  107800.0  107200.0  107200.0
          Center Point      81600.0   81700.0   81500.0   81300.0   81700.0
          Centreville       96200.0   96600.0   98000.0   99400.0   99700.0
          Chalkville        94500.0   94500.0   94500.0   94300.0   94300.0
          Chancellor            NaN       NaN       NaN       NaN       NaN
          Chelsea          167300.0  167200.0  167000.0  166500.0  166700.0
          Chickasaw         54100.0   54400.0   54900.0   55500.0   56000.0
          Chunchula         81700.0   82000.0   82300.0   82300.0   82800.0
          Citronelle        66800.0   67900.0   68400.0   67900.0   67900.0
          Clay             123200.0  123900.0  123900.0  124100.0  125300.0
          Coden             65100.0   65400.0   66800.0   68400.0   68700.0
          Coker            120000.0  118900.0  117900.0  117700.0  116900.0
          Concord           79000.0   79500.0   80100.0   80800.0   81700.0
          Cottondale       103200.0  104000.0  104800.0  105500.0  105600.0
...                             ...       ...       ...       ...       ...
Wisconsin Vandenbroek           NaN       NaN       NaN       NaN       NaN
          Vernon           176000.0  174600.0  174000.0  174300.0  175300.0
          Vienna           181600.0  181500.0  182300.0  183500.0  184900.0
          Vinland          129300.0  132800.0  135700.0  136300.0  136400.0
          Wales                 NaN       NaN       NaN       NaN       NaN
          Waterford        119200.0  119600.0  120100.0  120900.0  121200.0
          Waukesha         137200.0  136700.0  136600.0  136900.0  137900.0
          Waunakee         192300.0  192000.0  192600.0  193400.0  193400.0
          Waupun            84200.0   84300.0   84400.0   84500.0   84700.0
          Wausau            69200.0   70200.0   71300.0   71600.0   70500.0
          Wayne                 NaN       NaN       NaN       NaN       NaN
          West Allis        82500.0   83900.0   84600.0   83700.0   81900.0
          Weston            83100.0   83600.0   84100.0   84800.0   85400.0
          Wheatland        132800.0  134200.0  134900.0  135700.0  136900.0
          Whitelaw         104300.0  106400.0  108200.0  109500.0  112100.0
          Williams Bay     113600.0  111600.0  110400.0  110300.0  110500.0
          Wilson           129800.0  131400.0  132300.0  133600.0  135600.0
          Wind Lake        124100.0  124100.0  123700.0  124600.0  125400.0
          Wind Point       143000.0  141400.0  140200.0  141000.0  144100.0
          Wisconsin Dells  104100.0  104400.0  105000.0  105600.0  105300.0
          Wolf River       100500.0  102200.0  104100.0  105100.0  106100.0
          Woodruff              NaN       NaN       NaN       NaN       NaN
          Woodville             NaN       NaN       NaN       NaN       NaN
          Yorkville        133500.0  133400.0  134600.0  137100.0  138900.0
Wyoming   Bar Nunn          88700.0   88400.0   88600.0   89700.0   91100.0
          Burns            105700.0  107000.0  108200.0  109900.0  111700.0
          Casper            89100.0   89000.0   89500.0   90700.0   92100.0
          Cheyenne         120800.0  121000.0  121400.0  122200.0  123000.0
          Evansville       130000.0  130900.0  130600.0  131000.0  132300.0
          Pine Bluffs       95000.0   94100.0   94200.0   95600.0   97200.0

                             ...      2015-11   2015-12   2016-01   2016-02  \
State     RegionName         ...
Alabama   Adamsville         ...      73900.0   73500.0   73600.0   74100.0
          Alabaster          ...     151800.0  152400.0  152800.0  153400.0
          Albertville        ...      91600.0   91500.0   91400.0   92000.0
          Arab               ...     112500.0  112100.0  111000.0  109800.0
          Ardmore            ...     144200.0  143100.0  142200.0  142500.0
          Axis               ...     109500.0  109000.0  109600.0  110300.0
          Baileyton          ...      97200.0   97400.0   97200.0   96600.0
          Bay Minette        ...     121700.0  122000.0  121300.0  120300.0
          Bayou La Batre     ...      48900.0   48600.0   48700.0   48700.0
          Bessemer           ...      59500.0   59600.0   59600.0   59800.0
          Birmingham         ...      63200.0   62600.0   62400.0   62000.0
          Boaz               ...      86700.0   86400.0   85700.0   85700.0
          Brent              ...      96000.0   95200.0   94400.0   94700.0
          Brighton           ...      45900.0   45300.0   44700.0   44800.0
          Brookwood          ...     118400.0  118100.0  116600.0  114900.0
          Buhl               ...     146400.0  146300.0  142300.0  138900.0
          Calera             ...     128500.0  128800.0  129300.0  129700.0
          Center Point       ...      80800.0   81100.0   81600.0   82000.0
          Centreville        ...     101900.0  102200.0  103300.0  103700.0
          Chalkville         ...     111300.0  110600.0  110800.0  111700.0
          Chancellor         ...     110000.0  109700.0  110900.0  113200.0
          Chelsea            ...     208000.0  208600.0  209100.0  209000.0
          Chickasaw          ...      58500.0   58400.0   58100.0   57700.0
          Chunchula          ...     123800.0  123100.0  122800.0  122500.0
          Citronelle         ...      94100.0   93200.0   93000.0   93400.0
          Clay               ...     141700.0  142200.0  142700.0  143000.0
          Coden              ...      80500.0   80300.0   80700.0   81200.0
          Coker              ...     155300.0  155400.0  152800.0  150400.0
          Concord            ...     111000.0  112300.0  112800.0  112400.0
          Cottondale         ...     138000.0  138000.0  136100.0  134000.0
...                          ...          ...       ...       ...       ...
Wisconsin Vandenbroek        ...     206400.0  208000.0  208700.0  209900.0
          Vernon             ...     263200.0  263300.0  262800.0  263700.0
          Vienna             ...     282000.0  281800.0  281600.0  284200.0
          Vinland            ...     182100.0  182300.0  182500.0  183000.0
          Wales              ...     267600.0  267600.0  266900.0  267800.0
          Waterford          ...     230200.0  229800.0  230300.0  230400.0
          Waukesha           ...     190500.0  190900.0  190500.0  190900.0
          Waunakee           ...     297500.0  297300.0  297700.0  299600.0
          Waupun             ...     109800.0  109500.0  109400.0  110600.0
          Wausau             ...      94700.0   93700.0   93600.0   93700.0
          Wayne              ...     256600.0  258000.0  259800.0  262200.0
          West Allis         ...      99900.0  101700.0  102000.0  100800.0
          Weston             ...     138800.0  139000.0  139800.0  140300.0
          Wheatland          ...     176200.0  177500.0  179200.0  182300.0
          Whitelaw           ...     117900.0  118200.0  117800.0  117200.0
          Williams Bay       ...     225700.0  226600.0  229100.0  230700.0
          Wilson             ...     177400.0  178800.0  179250.0  179500.0
          Wind Lake          ...     241700.0  241700.0  241600.0  240700.0
          Wind Point         ...     249400.0  252000.0  254000.0  254100.0
          Wisconsin Dells    ...     140600.0  139700.0  139400.0  139700.0
          Wolf River         ...     163200.0  162100.0  160200.0  159300.0
          Woodruff           ...     165600.0  163900.0  162800.0  162400.0
          Woodville          ...     182100.0  183000.0  183100.0  182400.0
          Yorkville          ...     244100.0  246500.0  248800.0  248800.0
Wyoming   Bar Nunn           ...     211500.0  211200.0  211200.0  210300.0
          Burns              ...     164100.0  164500.0  166800.0  168500.0
          Casper             ...     182300.0  182600.0  184000.0  184500.0
          Cheyenne           ...     190500.0  191900.0  193800.0  194700.0
          Evansville         ...     303900.0  306600.0  308200.0  309700.0
          Pine Bluffs        ...     169600.0  169300.0  168400.0  166300.0

                            2016-03   2016-04   2016-05   2016-06   2016-07  \
State     RegionName
Alabama   Adamsville        74800.0   75200.0   74900.0   74700.0   74700.0
          Alabaster        154200.0  154900.0  155200.0  155200.0  155600.0
          Albertville       92600.0   92600.0   92400.0   92400.0   92300.0
          Arab             109300.0  109500.0  110100.0  110700.0  111600.0
          Ardmore          143000.0  143200.0  143400.0  143100.0  142300.0
          Axis             110900.0  111700.0  112300.0  112600.0  112800.0
          Baileyton         96500.0   97500.0   99100.0  100100.0  101300.0
          Bay Minette      119200.0  118500.0  118300.0  118200.0  118300.0
          Bayou La Batre    48300.0   47800.0   47800.0   47900.0   47600.0
          Bessemer          59900.0   59700.0   59900.0   60000.0   59900.0
          Birmingham        61700.0   61600.0   61700.0   61600.0   61300.0
          Boaz              86500.0   87100.0   87300.0   87700.0   88300.0
          Brent             94200.0   93200.0   91500.0   89400.0   87900.0
          Brighton          45600.0   45500.0   44400.0   43400.0   43700.0
          Brookwood        114200.0  113500.0  111900.0  110500.0  109200.0
          Buhl             138200.0  137500.0  135800.0  133400.0  130000.0
          Calera           129900.0  130000.0  130000.0  129800.0  129600.0
          Center Point      82500.0   82800.0   83000.0   83300.0   83800.0
          Centreville      102700.0  101500.0  100400.0   99000.0   98400.0
          Chalkville       113000.0  113800.0  114400.0  115000.0  115600.0
          Chancellor       115800.0  118800.0  120800.0  121400.0  121500.0
          Chelsea          209500.0  210500.0  211500.0  212200.0  213500.0
          Chickasaw         57500.0   57200.0   57000.0   57000.0   56800.0
          Chunchula        122200.0  122500.0  123400.0  124100.0  124300.0
          Citronelle        93700.0   93900.0   94000.0   94000.0   93800.0
          Clay             143400.0  144000.0  144500.0  145000.0  145600.0
          Coden             81400.0   81900.0   82300.0   81900.0   81000.0
          Coker            149700.0  149000.0  147200.0  145400.0  144000.0
          Concord          111800.0  111500.0  111700.0  112600.0  113600.0
          Cottondale       133400.0  133900.0  134200.0  134000.0  133600.0
...                             ...       ...       ...       ...       ...
Wisconsin Vandenbroek      212100.0  214400.0  216800.0  218800.0  221700.0
          Vernon           265500.0  266900.0  268400.0  269200.0  272000.0
          Vienna           286600.0  286100.0  285500.0  285800.0  288100.0
          Vinland          183900.0  185100.0  186400.0  188000.0  189400.0
          Wales            270600.0  273400.0  276200.0  277400.0  280300.0
          Waterford        230900.0  233200.0  235200.0  236100.0  237000.0
          Waukesha         192000.0  193200.0  194200.0  194500.0  197000.0
          Waunakee         300800.0  301600.0  303200.0  304600.0  306700.0
          Waupun           112300.0  112800.0  112600.0  112400.0  112600.0
          Wausau            94500.0   95800.0   96900.0   97800.0   98200.0
          Wayne            263600.0  264900.0  266900.0  269600.0  271700.0
          West Allis        99900.0  100000.0   97900.0   95800.0   95600.0
          Weston           140400.0  140900.0  142100.0  143700.0  144700.0
          Wheatland        185200.0  187300.0  189000.0  190700.0  193000.0
          Whitelaw         116700.0  116800.0  117400.0  118000.0  117800.0
          Williams Bay     234900.0  242800.0  250100.0  252300.0  254000.0
          Wilson           180550.0  182750.0  186100.0  189350.0  191550.0
          Wind Lake        240200.0  242000.0  244000.0  245600.0  247700.0
          Wind Point       255100.0  258300.0  260900.0  259300.0  258100.0
          Wisconsin Dells  140200.0  140700.0  140900.0  141400.0  142500.0
          Wolf River       159000.0  158800.0  160200.0  163800.0  167100.0
          Woodruff         162400.0  161900.0  161600.0  162400.0  163700.0
          Woodville        182400.0  184000.0  186700.0  189300.0  192000.0
          Yorkville        247800.0  250400.0  255300.0  259900.0  264100.0
Wyoming   Bar Nunn         209100.0  209000.0  209000.0  208500.0  207700.0
          Burns            169500.0  171100.0  172100.0  171600.0  170700.0
          Casper           184500.0  184900.0  185400.0  185200.0  184600.0
          Cheyenne         194800.0  195500.0  196400.0  197600.0  198800.0
          Evansville       310400.0  310200.0  308800.0  308600.0  308800.0
          Pine Bluffs      165800.0  166600.0  164500.0  160300.0  158000.0

                            2016-08
State     RegionName
Alabama   Adamsville        74700.0
          Alabaster        156100.0
          Albertville       92100.0
          Arab             112400.0
          Ardmore          141600.0
          Axis             112700.0
          Baileyton        103100.0
          Bay Minette      118700.0
          Bayou La Batre    47200.0
          Bessemer          59700.0
          Birmingham        61200.0
          Boaz              88900.0
          Brent             87400.0
          Brighton          44300.0
          Brookwood        108100.0
          Buhl             126700.0
          Calera           129600.0
          Center Point      84200.0
          Centreville       98600.0
          Chalkville       115800.0
          Chancellor       121500.0
          Chelsea          214900.0
          Chickasaw         56400.0
          Chunchula        124400.0
          Citronelle        93700.0
          Clay             146100.0
          Coden             80100.0

In [17]:
house_quarter = house.iloc[:,:2].copy()  # 得到结构
for i in range(1,int(len(house.columns)/3)+1):
    ye_mo = house.columns[3*i-1]
    name = ye_mo[:4]+'q'+str(int(int(ye_mo[-2:])/3))  #生成名字
    house_quarter = pd.merge(house_quarter,pd.DataFrame(house.iloc[:,3*i-3:3*i].mean(axis = 1),columns= [name]),left_index=True,right_index=True)
    # 将新的到的和原来合并
house_quarter = pd.merge(house_quarter,pd.DataFrame(house.iloc[:,-2:].mean(axis = 1),columns= ['2016q3']),left_index=True,right_index=True)
# 最后剩两个单独处理
house_quarter.drop(['2000-01','2000-02'],axis=1,inplace=True)
house_quarter

                                  2000q1         2000q2         2000q3  \
State     RegionName
Alabama   Adamsville        69033.333333   69166.666667   69800.000000
          Alabaster        122133.333333  123066.666667  123166.666667
          Albertville       73966.666667   72600.000000   72833.333333
          Arab              83766.666667   81566.666667   81333.333333
          Ardmore                    NaN            NaN            NaN
          Axis                       NaN            NaN            NaN
          Baileyton                  NaN            NaN            NaN
          Bay Minette       81700.000000   78533.333333   79133.333333
          Bayou La Batre    44066.666667   44500.000000   44266.666667
          Bessemer                   NaN            NaN            NaN
          Birmingham        54033.333333   54400.000000   54966.666667
          Boaz              70866.666667   70266.666667   70300.000000
          Brent             92933.333333   94333.333333   96166.666667
          Brighton                   NaN            NaN            NaN
          Brookwood         92566.666667   95100.000000   98866.666667
          Buhl              90800.000000   94600.000000   96500.000000
          Calera           108933.333333  110366.666667  108000.000000
          Center Point      80966.666667   81233.333333   81500.000000
          Centreville       95300.000000   96566.666667   98000.000000
          Chalkville        94100.000000   94433.333333   94433.333333
          Chancellor                 NaN            NaN            NaN
          Chelsea          162066.666667  167033.333333  166900.000000
          Chickasaw         51200.000000   53666.666667   54933.333333
          Chunchula         80266.666667   81766.666667   82200.000000
          Citronelle        64833.333333   66633.333333   68066.666667
          Clay             120900.000000  122266.666667  123966.666667
          Coden             62600.000000   64800.000000   66866.666667
          Coker            118100.000000  120766.666667  118166.666667
          Concord           78600.000000   78700.000000   80133.333333
          Cottondale       100833.333333  102633.333333  104766.666667
...                                  ...            ...            ...
Wisconsin Vandenbroek                NaN            NaN            NaN
          Vernon           183200.000000  178200.000000  174300.000000
          Vienna           178033.333333  181533.333333  182433.333333
          Vinland          119800.000000  126766.666667  134933.333333
          Wales                      NaN            NaN            NaN
          Waterford        121200.000000  119433.333333  120200.000000
          Waukesha         141266.666667  138433.333333  136733.333333
          Waunakee         187400.000000  191433.333333  192666.666667
          Waupun            84000.000000   84000.000000   84400.000000
          Wausau            69566.666667   69466.666667   71033.333333
          Wayne                      NaN            NaN            NaN
          West Allis        80933.333333   81933.333333   84066.666667
          Weston            80166.666667   82700.000000   84166.666667
          Wheatland        129800.000000  132133.333333  134933.333333
          Whitelaw          96033.333333  101433.333333  108033.333333
          Williams Bay     122900.000000  115300.000000  110766.666667
          Wilson           129033.333333  129366.666667  132433.333333
          Wind Lake        124366.666667  123666.666667  124133.333333
          Wind Point       149233.333333  145266.666667  140866.666667
          Wisconsin Dells  100000.000000  103400.000000  105000.000000
          Wolf River        95166.666667   99333.333333  103800.000000
          Woodruff                   NaN            NaN            NaN
          Woodville                  NaN            NaN            NaN
          Yorkville        139066.666667  134900.000000  135033.333333
Wyoming   Bar Nunn          93033.333333   89666.666667   88900.000000
          Burns            101533.333333  104566.666667  108366.666667
          Casper            89233.333333   89600.000000   89733.333333
          Cheyenne         116866.666667  120033.333333  121533.333333
          Evansville       128033.333333  128766.666667  130833.333333
          Pine Bluffs       93733.333333   95066.666667   94633.333333

                                  2000q4         2001q1         2001q2  \
State     RegionName
Alabama   Adamsville        71966.666667   73466.666667   74000.000000
          Alabaster        123700.000000  123233.333333  125133.333333
          Albertville       74200.000000   75900.000000   76000.000000
          Arab              82966.666667   84200.000000   84533.333333
          Ardmore                    NaN            NaN            NaN
          Axis                       NaN            NaN            NaN
          Baileyton                  NaN            NaN            NaN
          Bay Minette       81300.000000   85700.000000   87266.666667
          Bayou La Batre    43666.666667   42500.000000   43333.333333
          Bessemer                   NaN            NaN            NaN
          Birmingham        56066.666667   56833.333333   57600.000000
          Boaz              71466.666667   72833.333333   71900.000000
          Brent             98333.333333   96533.333333   98500.000000
          Brighton                   NaN            NaN            NaN
          Brookwood         99966.666667  101666.666667  103666.666667
          Buhl              96566.666667   99266.666667  101966.666667
          Calera           107933.333333  109333.333333  112200.000000
          Center Point      82233.333333   83366.666667   84333.333333
          Centreville       99366.666667   98100.000000   99266.666667
          Chalkville        94433.333333   96066.666667   97433.333333
          Chancellor                 NaN            NaN            NaN
          Chelsea          167400.000000  170633.333333  174300.000000
          Chickasaw         56066.666667   55133.333333   53566.666667
          Chunchula         83400.000000   85400.000000   86100.000000
          Citronelle        67766.666667   67866.666667   70000.000000
          Clay             126500.000000  128033.333333  128300.000000
          Coden             68566.666667   68933.333333   71300.000000
          Coker            115333.333333  114066.666667  115700.000000
          Concord           82800.000000   85133.333333   85800.000000
          Cottondale       105300.000000  106733.333333  109233.333333
...                                  ...            ...            ...
Wisconsin Vandenbroek                NaN            NaN            NaN
          Vernon           177466.666667  186233.333333  190500.000000
          Vienna           186300.000000  190600.000000  191566.666667
          Vinland          137833.333333  144300.000000  148200.000000
          Wales                      NaN            NaN            NaN
          Waterford        121966.666667  127000.000000  133000.000000
          Waukesha         139833.333333  147600.000000  151066.666667
          Waunakee         193733.333333  197333.333333  198500.000000
          Waupun            84533.333333   85100.000000   86600.000000
          Wausau            69833.333333   69866.666667   71366.666667
          Wayne                      NaN            NaN            NaN
          West Allis        80666.666667   79100.000000   80333.333333
          Weston            85800.000000   87266.666667   88500.000000
          Wheatland        137833.333333  142566.666667  143000.000000
          Whitelaw         114000.000000  116333.333333  114966.666667
          Williams Bay     110700.000000  112600.000000  117100.000000
          Wilson           137200.000000  143533.333333  143833.333333
          Wind Lake        126066.666667  132133.333333  139466.666667
          Wind Point       147866.666667  158666.666667  163966.666667
          Wisconsin Dells  105433.333333  105533.333333  107100.000000
          Wolf River       107633.333333  111400.000000  115033.333333
          Woodruff                   NaN            NaN            NaN
          Woodville                  NaN            NaN            NaN
          Yorkville        140300.000000  148800.000000  155233.333333
Wyoming   Bar Nunn          93500.000000   98833.333333   99900.000000
          Burns            113000.000000  115833.333333  117200.000000
          Casper            93166.666667   95500.000000   97633.333333
          Cheyenne         123633.333333  125533.333333  126300.000000
          Evansville       132066.666667  130566.666667  131433.333333
          Pine Bluffs       98066.666667  103233.333333  104600.000000

                                  2001q3         2001q4         2002q1  \
State     RegionName
Alabama   Adamsville        73333.333333   73100.000000   73333.333333
          Alabaster        127766.666667  127200.000000  127300.000000
          Albertville       72066.666667   73566.666667   76533.333333
          Arab              81666.666667   83900.000000   87266.666667
          Ardmore                    NaN            NaN            NaN
          Axis                       NaN            NaN            NaN
          Baileyton                  NaN            NaN            NaN
          Bay Minette       85900.000000   85000.000000   84066.666667
          Bayou La Batre    45433.333333   45400.000000   45400.000000
          Bessemer                   NaN            NaN            NaN
          Birmingham        58433.333333   58700.000000   59500.000000
          Boaz              68733.333333   69833.333333   72766.666667
          Brent             99366.666667  104100.000000  103800.000000
          Brighton                   NaN            NaN            NaN
          Brookwood        101833.333333   99900.000000   99633.333333
          Buhl             102000.000000  102733.333333  102533.333333
          Calera           114333.333333  112133.333333  111500.000000
          Center Point      84466.666667   85333.333333   86100.000000
          Centreville      100400.000000  104633.333333  105233.333333
          Chalkville        98400.000000   99366.666667   99866.666667
          Chancellor                 NaN            NaN            NaN
          Chelsea          174900.000000  173300.000000  170566.666667
          Chickasaw         53533.333333   53400.000000   54266.666667
          Chunchula         86733.333333   86566.666667   86166.666667
          Citronelle        71466.666667   70933.333333   69833.333333
          Clay             129233.333333  130466.666667  130900.000000
          Coden             72733.333333   73600.000000   72933.333333
          Coker            118833.333333  122566.666667  122366.666667
          Concord           84866.666667   84766.666667   86366.666667
          Cottondale       109200.000000  109900.000000  109333.333333
...                                  ...            ...            ...
Wisconsin Vandenbroek                NaN            NaN            NaN
          Vernon           193100.000000  197466.666667  201800.000000
          Vienna           193733.333333  194833.333333  198466.666667
          Vinland          147733.333333  151200.000000  149233.333333
          Wales                      NaN            NaN            NaN
          Waterford        139233.333333  143100.000000  145733.333333
          Waukesha         153100.000000  155033.333333  158200.000000
          Waunakee         201266.666667  202100.000000  206100.000000
          Waupun            87666.666667   87100.000000   87533.333333
          Wausau            73100.000000   74033.333333   76400.000000
          Wayne                      NaN            NaN            NaN
          West Allis        81433.333333   82400.000000   84966.666667
          Weston            90066.666667   91766.666667   94833.333333
          Wheatland        143966.666667  142633.333333  143933.333333
          Whitelaw         115666.666667  115866.666667  117766.666667
          Williams Bay     119533.333333  121400.000000  126566.666667
          Wilson           143233.333333  141966.666667  142466.666667
          Wind Lake        144200.000000  147333.333333  150933.333333
          Wind Point       170833.333333  169566.666667  170533.333333
          Wisconsin Dells  109866.666667  111633.333333  115833.333333
          Wolf River       116900.000000  118233.333333  118600.000000
          Woodruff                   NaN            NaN            NaN
          Woodville                  NaN            NaN            NaN
          Yorkville        161133.333333  162800.000000  164866.666667
Wyoming   Bar Nunn          99100.000000   98333.333333   98633.333333
          Burns            117800.000000  117633.333333  117333.333333
          Casper            99433.333333  100633.333333  101733.333333
          Cheyenne         126466.666667  128133.333333  128466.666667
          Evansville       132400.000000  133466.666667  133300.000000
          Pine Bluffs      106500.000000  104066.666667  102233.333333

                                  2002q2    ...            2014q2  \
State     RegionName                        ...
Alabama   Adamsville        73133.333333    ...      77066.666667
          Alabaster        128000.000000    ...     147133.333333
          Albertville       76366.666667    ...      84033.333333
          Arab              87700.000000    ...     113366.666667
          Ardmore                    NaN    ...     140533.333333
          Axis                       NaN    ...     111066.666667
          Baileyton                  NaN    ...      87666.666667
          Bay Minette       84566.666667    ...     113333.333333
          Bayou La Batre    45566.666667    ...      49800.000000
          Bessemer                   NaN    ...      54600.000000
          Birmingham        59866.666667    ...      61733.333333
          Boaz              72100.000000    ...      80933.333333
          Brent            102533.333333    ...      93866.666667
          Brighton                   NaN    ...      45366.666667
          Brookwood        100366.666667    ...     106633.333333
          Buhl             100100.000000    ...     119233.333333
          Calera           111233.333333    ...     125533.333333
          Center Point      86500.000000    ...      78833.333333
          Centreville      105066.666667    ...      95566.666667
          Chalkville       100733.333333    ...     105233.333333
          Chancellor                 NaN    ...     116400.000000
          Chelsea          171100.000000    ...     197133.333333
          Chickasaw         55000.000000    ...      59000.000000
          Chunchula         86533.333333    ...     120666.666667
          Citronelle        68133.333333    ...      88600.000000
          Clay             131100.000000    ...     134100.000000
          Coden             69100.000000    ...      77566.666667
          Coker            119200.000000    ...     141700.000000
          Concord           90366.666667    ...     104733.333333
          Cottondale       107966.666667    ...     128500.000000
...                                  ...    ...               ...
Wisconsin Vandenbroek                NaN    ...     195400.000000
          Vernon           201966.666667    ...     257733.333333
          Vienna           202466.666667    ...     265700.000000
          Vinland          146433.333333    ...     181766.666667
          Wales                      NaN    ...     262133.333333
          Waterford        151266.666667    ...     213133.333333
          Waukesha         157833.333333    ...     181166.666667
          Waunakee         208533.333333    ...     278100.000000
          Waupun            87466.666667    ...     113166.666667
          Wausau            78700.000000    ...      91600.000000
          Wayne                      NaN    ...     238633.333333
          West Allis        87566.666667    ...      90433.333333
          Weston            97600.000000    ...     133233.333333
          Wheatland        146433.333333    ...     169266.666667
          Whitelaw         116800.000000    ...     120433.333333
          Williams Bay     131700.000000    ...     223000.000000
          Wilson           139200.000000    ...     165116.666667
          Wind Lake        156166.666667    ...     228200.000000
          Wind Point       179733.333333    ...     261233.333333
          Wisconsin Dells  117333.333333    ...     137500.000000
          Wolf River       116800.000000    ...     162666.666667
          Woodruff                   NaN    ...     172133.333333
          Woodville                  NaN    ...     162600.000000
          Yorkville        172466.666667    ...     231500.000000
Wyoming   Bar Nunn         100866.666667    ...     199233.333333
          Burns            117233.333333    ...     168866.666667
          Casper           101533.333333    ...     175766.666667
          Cheyenne         129633.333333    ...     177466.666667
          Evansville       131066.666667    ...     296733.333333
          Pine Bluffs      103566.666667    ...     148666.666667

                                  2014q3         2014q4         2015q1  \
State     RegionName
Alabama   Adamsville        75966.666667   71900.000000   71666.666667
          Alabaster        147633.333333  148700.000000  148900.000000
          Albertville       84766.666667   86800.000000   88466.666667
          Arab             111700.000000  111600.000000  110166.666667
          Ardmore          139566.666667  140900.000000  143233.333333
          Axis             111833.333333  111800.000000  109533.333333
          Baileyton         90033.333333   94100.000000   94600.000000
          Bay Minette      110600.000000  109900.000000  111100.000000
          Bayou La Batre    51000.000000   51766.666667   50733.333333
          Bessemer          55333.333333   54733.333333   55200.000000
          Birmingham        60900.000000   59533.333333   59900.000000
          Boaz              81866.666667   82866.666667   83966.666667
          Brent             97100.000000  100100.000000  102433.333333
          Brighton          45133.333333   43766.666667   42500.000000
          Brookwood        110233.333333  114366.666667  117700.000000
          Buhl             132033.333333  138400.000000  141766.666667
          Calera           126733.333333  127633.333333  128366.666667
          Center Point      78433.333333   80200.000000   80100.000000
          Centreville       98866.666667  101866.666667  103933.333333
          Chalkville       104333.333333  105866.666667  106966.666667
          Chancellor       117000.000000  117133.333333  114733.333333
          Chelsea          199066.666667  199933.333333  202333.333333
          Chickasaw         60400.000000   59733.333333   58066.666667
          Chunchula        121600.000000  122733.333333  123666.666667
          Citronelle        89633.333333   90766.666667   91300.000000
          Clay             134300.000000  135466.666667  138466.666667
          Coden             76866.666667   77800.000000   79300.000000
          Coker            146300.000000  154333.333333  157566.666667
          Concord          100233.333333   94800.000000   96200.000000
          Cottondale       130566.666667  133433.333333  134500.000000
...                                  ...            ...            ...
Wisconsin Vandenbroek      197366.666667  202566.666667  204466.666667
          Vernon           256200.000000  254566.666667  253633.333333
          Vienna           267466.666667  267766.666667  268300.000000

前面进行了数据的清理，使用的是pandas库，而最后一问需要用到scipy科学计算库，这一块还没学，所以过一段时间再做。